# -*- coding: utf-8 -*-
GRADE_9_DATA = {
    "warmup": [
        {"id": "g9-wu-6", "text": "Hệ thức của định luật Ohm cho đoạn mạch là gì?", "answer": "I = U / R"},
        {"id": "g9-wu-7", "text": "Định lý Viète phát biểu tổng hai nghiệm x1 + x2 của phương trình bậc hai ax^2 + bx + c = 0 bằng bao nhiêu?", "answer": "-b / a"},
        {"id": "g9-wu-8", "text": "Hiđrocacbon no đơn giản nhất trong thành phần chính của khí thiên nhiên và khí bùn ao là gì?", "answer": "Metan (CH4)"},
        {"id": "g9-wu-9", "text": "Hình tượng anh bộ đội cụ Hồ trong thời kỳ kháng chiến chống Pháp được khắc họa xúc động qua bài thơ 'Đồng chí' của nhà thơ nào?", "answer": "Chính Hữu"},
        {"id": "g9-wu-10", "text": "Bộ nhiễm sắc thể lưỡng bội (2n) ở loài người bình thường gồm bao nhiêu chiếc?", "answer": "46 chiếc (23 cặp)"},
        {"id": "g9-wu-11", "text": "Tứ giác nội tiếp đường tròn khi và chỉ khi tổng số đo hai góc đối diện bằng bao nhiêu độ?", "answer": "180 độ"},
        {"id": "g9-wu-12", "text": "Định luật Joule - Lenz xác định nhiệt lượng tỏa ra trên dây dẫn theo công thức nào?", "answer": "Q = I^2 . R . t"},
        {"id": "g9-wu-13", "text": "Nhóm chức đặc trưng cho phân tử rượu (ancol) như rượu etylic là nhóm gì?", "answer": "Nhóm hiđroxyl (-OH)"},
        {"id": "g9-wu-14", "text": "Vùng kinh tế nào có quy mô sản xuất công nghiệp và thu hút vốn đầu tư nước ngoài (FDI) lớn nhất nước ta?", "answer": "Đông Nam Bộ"},
        {"id": "g9-wu-15", "text": "Cặp bazơ nitơ nào sau đây liên kết với nhau bằng 2 liên kết hiđro theo nguyên tắc bổ sung trong phân tử ADN?", "answer": "A liên kết với T (A - T)"},
        {"id": "g9-wu-16", "text": "Căn bậc hai số học của một số thực a không âm được ký hiệu là gì?", "answer": "Căn a"},
        {"id": "g9-wu-17", "text": "Hiện tượng tia sáng bị đổi hướng truyền khi đi từ môi trường trong suốt này sang môi trường trong suốt khác gọi là gì?", "answer": "Khúc xạ ánh sáng"},
        {"id": "g9-wu-18", "text": "Dung dịch brom có màu vàng nâu bị mất màu khi cho khí hiđrocacbon không no nào sau đây sục vào?", "answer": "Etilen (hoặc Axetilen)"},
        {"id": "g9-wu-19", "text": "Truyện ngắn 'Làng' thể hiện tình yêu làng gắn liền với tình yêu đất nước của nhân vật ông Hai do nhà văn nào sáng tác?", "answer": "Kim Lân"},
        {"id": "g9-wu-20", "text": "Hội nghị thành lập Đảng Cộng sản Việt Nam đầu năm 1930 do ai chủ trì?", "answer": "Nguyễn Ái Quốc (Hồ Chí Minh)"},
        {"id": "g9-wu-21", "text": "Đường kính của hình cầu bằng 2R thì công thức tính thể tích khối cầu là gì?", "answer": "V = 4/3 . pi . R^3"},
        {"id": "g9-wu-22", "text": "Kim loại nào dẫn điện tốt nhất trong tất cả các kim loại?", "answer": "Bạc (Ag)"},
        {"id": "g9-wu-23", "text": "Hiện tượng xuất hiện dòng điện trong cuộn dây dẫn kín khi số đường sức từ xuyên qua tiết diện cuộn dây biến thiên gọi là hiện tượng gì?", "answer": "Cảm ứng điện từ"},
        {"id": "g9-wu-24", "text": "Quá trình phân bào nào tạo ra các giao tử mang bộ nhiễm sắc thể đơn bội (n)?", "answer": "Giảm phân"},
        {"id": "g9-wu-25", "text": "Tỉnh nào ở vùng Tây Nguyên được mệnh danh là 'thủ phủ cà phê' của Việt Nam?", "answer": "Đắk Lắk (thành phố Buôn Ma Thuột)"},
        {"id": "g9-wu-26", "text": "Trong một đường tròn, góc nội tiếp có số đo bằng bao nhiêu phần số đo của cung bị chắn?", "answer": "Một nửa (1/2 số đo cung bị chắn)"},
        {"id": "g9-wu-27", "text": "Axit axetic (CH3COOH) có nồng độ từ 2% đến 5% trong nước thường được gọi trong đời sống hàng ngày là gì?", "answer": "Giấm ăn"},
        {"id": "g9-wu-28", "text": "Vật kính của kính hiển vi quang học và kính lúp thông thường đều là loại thấu kính gì?", "answer": "Thấu kính hội tụ"},
        {"id": "g9-wu-29", "text": "Nhân vật anh thanh niên làm công tác khí tượng kiêm vật lý địa cầu trong tác phẩm 'Lặng lẽ Sa Pa' là sáng tác của ai?", "answer": "Nguyễn Thành Long"},
        {"id": "g9-wu-30", "text": "Chiến thắng quân sự nào của quân và dân ta năm 1954 đã đập tan tập đoàn cứ điểm mạnh nhất của thực dân Pháp ở Đông Dương?", "answer": "Chiến thắng Điện Biên Phủ"},
        {"id": "g9-wu-31", "text": "Biệt thức Delta (Δ) của phương trình bậc hai ax^2 + bx + c = 0 được tính bằng công thức nào?", "answer": "Delta = b^2 - 4ac"},
        {"id": "g9-wu-32", "text": "Chất béo (triglyceride) khi đun nóng với dung dịch kiềm NaOH xảy ra phản ứng thủy phân gọi là phản ứng gì?", "answer": "Phản ứng xà phòng hóa"},
        {"id": "g9-wu-33", "text": "Bộ phận nhạy cảm với ánh sáng nằm ở đáy mắt, đóng vai trò như màn ảnh hứng ảnh của vật gọi là gì?", "answer": "Màng lưới (võng mạc)"},
        {"id": "g9-wu-34", "text": "Hội chứng di truyền nào ở người do thừa 1 nhiễm sắc thể ở cặp số 21 (ba nhiễm sắc thể 21)?", "answer": "Hội chứng Down (Đao)"},
        {"id": "g9-wu-35", "text": "Đảo nào có diện tích lớn nhất Việt Nam, trực thuộc tỉnh Kiên Giang?", "answer": "Đảo Phú Quốc"},
        {"id": "g9-wu-36", "text": "Hai tiếp tuyến của một đường tròn cắt nhau tại một điểm thì điểm đó cách đều hai yếu tố nào?", "answer": "Hai tiếp điểm"},
        {"id": "g9-wu-37", "text": "Hợp kim của sắt với cacbon trong đó hàm lượng cacbon dưới 2% được gọi là gì?", "answer": "Thép"},
        {"id": "g9-wu-38", "text": "Máy biến thế có số vòng dây cuộn sơ cấp lớn hơn cuộn thứ cấp là máy tăng thế hay hạ thế?", "answer": "Máy hạ thế"},
        {"id": "g9-wu-39", "text": "Thành phần biệt lập nào trong câu được dùng để thể hiện cách nhìn của người nói đối với mức độ tin cậy của sự việc (ví dụ: dường như, có lẽ)?", "answer": "Thành phần tình thái"},
        {"id": "g9-wu-40", "text": "Đại hội đại biểu toàn quốc lần thứ mấy của Đảng (năm 1986) đã đề ra đường lối Đổi mới đất nước?", "answer": "Đại hội VI (Đại hội 6)"}
    ],
    "acceleration": [
        {"id": "g9-tt-6", "text": "Phương trình bậc hai x^2 - 7x + 12 = 0 có hai nghiệm là:", "options": ["x = 3 và x = 4", "x = -3 và x = -4", "x = 2 và x = 6", "x = -2 và x = -6"], "answer": "x = 3 và x = 4", "timeLimitSeconds": 20},
        {"id": "g9-tt-7", "text": "Kim loại nào sau đây TÁC DỤNG ĐƯỢC với dung dịch muối FeSO4?", "options": ["Đồng (Cu)", "Bạc (Ag)", "Kẽm (Zn)", "Vàng (Au)"], "answer": "Kẽm (Zn)", "timeLimitSeconds": 20},
        {"id": "g9-tt-8", "text": "Một bóng đèn ghi 220V - 100W hoạt động bình thường ở hiệu điện thế 220V. Điện trở của bóng đèn là:", "options": ["220 ôm", "484 ôm", "100 ôm", "22 ôm"], "answer": "484 ôm", "timeLimitSeconds": 20},
        {"id": "g9-tt-9", "text": "Theo quy luật phân ly độc lập của Mendel, phép lai AaBb x AaBb cho tỉ lệ phân ly kiểu hình ở đời con là:", "options": ["9 : 3 : 3 : 1", "3 : 1", "1 : 2 : 1", "1 : 1 : 1 : 1"], "answer": "9 : 3 : 3 : 1", "timeLimitSeconds": 20},
        {"id": "g9-tt-10", "text": "Nhà máy lọc dầu đầu tiên của Việt Nam đặt tại địa phương nào?", "options": ["Dung Quất (Quảng Ngãi)", "Nghi Sơn (Thanh Hóa)", "Vũng Tàu (Bà Rịa - Vũng Tàu)", "Long Sơn"], "answer": "Dung Quất (Quảng Ngãi)", "timeLimitSeconds": 20},
        {"id": "g9-tt-11", "text": "Góc tạo bởi tia tiếp tuyến và dây cung có số đo bằng bao nhiêu so với cung bị chắn?", "options": ["Bằng số đo cung bị chắn", "Bằng một nửa số đo cung bị chắn", "Bằng hai lần số đo cung bị chắn", "Bằng 90 độ"], "answer": "Bằng một nửa số đo cung bị chắn", "timeLimitSeconds": 20},
        {"id": "g9-tt-12", "text": "Chất nào sau đây làm quỳ tím hóa đỏ và tác dụng với đá vôi (CaCO3) sinh ra khí CO2?", "options": ["C2H5OH", "CH3COOH", "CH4", "C6H12O6"], "answer": "CH3COOH", "timeLimitSeconds": 20},
        {"id": "g9-tt-13", "text": "Để giảm hao phí do tỏa nhiệt trên đường dây khi truyền tải điện năng đi xa, biện pháp tốt nhất là:", "options": ["Tăng tiết diện dây dẫn", "Tăng hiệu điện thế ở hai đầu đường dây", "Giảm chiều dài dây tải", "Dùng dây bạc"], "answer": "Tăng hiệu điện thế ở hai đầu đường dây", "timeLimitSeconds": 20},
        {"id": "g9-tt-14", "text": "Bài thơ 'Mùa xuân nho nhỏ' được nhà thơ Thanh Hải sáng tác trong hoàn cảnh nào?", "options": ["Trên giường bệnh trước khi qua đời", "Trên đường hành quân ra trận", "Trong nhà tù thực dân", "Khi đất nước vừa giải phóng"], "answer": "Trên giường bệnh trước khi qua đời", "timeLimitSeconds": 20},
        {"id": "g9-tt-15", "text": "Hệ phương trình bậc nhất: 2x + y = 5 và x - y = 1 có nghiệm (x; y) là:", "options": ["(2; 1)", "(3; 2)", "(1; 3)", "(4; -3)"], "answer": "(2; 1)", "timeLimitSeconds": 20},
        {"id": "g9-tt-16", "text": "Kim loại duy nhất có màu đỏ cam đặc trưng và dẫn nhiệt, dẫn điện rất tốt là:", "options": ["Nhôm", "Đồng", "Sắt", "Chì"], "answer": "Đồng", "timeLimitSeconds": 20},
        {"id": "g9-tt-17", "text": "Một người chỉ nhìn rõ các vật ở gần mà không nhìn rõ các vật ở xa mắt là người bị tật gì?", "options": ["Cận thị", "Viễn thị", "Loạn thị", "Lão thị"], "answer": "Cận thị", "timeLimitSeconds": 20},
        {"id": "g9-tt-18", "text": "Quá trình tự nhân đôi của phân tử ADN diễn ra theo những nguyên tắc nào?", "options": ["Nguyên tắc bổ sung và bán bảo toàn", "Nguyên tắc bảo tồn hoàn toàn", "Nguyên tắc ngẫu nhiên", "Nguyên tắc khuôn mẫu và phân kỳ"], "answer": "Nguyên tắc bổ sung và bán bảo toàn", "timeLimitSeconds": 20},
        {"id": "g9-tt-19", "text": "Vùng Đồng bằng sông Hồng có tài nguyên khoáng sản nào có trữ lượng hàng chục tỉ tấn nằm sâu trong lòng đất?", "options": ["Than nâu", "Bô-xít", "Apatit", "Dầu khí"], "answer": "Than nâu", "timeLimitSeconds": 20},
        {"id": "g9-tt-20", "text": "Diện tích toàn phần của hình trụ có bán kính đáy R và chiều cao h được tính bằng công thức:", "options": ["2.pi.R.h", "2.pi.R.h + 2.pi.R^2", "pi.R^2.h", "2.pi.R^2"], "answer": "2.pi.R.h + 2.pi.R^2", "timeLimitSeconds": 20},
        {"id": "g9-tt-21", "text": "Phản ứng đặc trưng của hiđrocacbon có liên kết đôi như Etilen (C2H4) là phản ứng gì?", "options": ["Phản ứng thế", "Phản ứng cộng", "Phản ứng este hóa", "Phản ứng trung hòa"], "answer": "Phản ứng cộng", "timeLimitSeconds": 20},
        {"id": "g9-tt-22", "text": "Tác phẩm 'Truyện Kiều' của đại thi hào Nguyễn Du ban đầu có tên gọi chữ Hán là gì?", "options": ["Đoạn trường tân thanh", "Kim Vân Kiều truyện", "Thanh Hiên thi tập", "Bắc hành tạp lục"], "answer": "Đoạn trường tân thanh", "timeLimitSeconds": 20},
        {"id": "g9-tt-23", "text": "Cặp nhiễm sắc thể giới tính ở người phụ nữ bình thường là gì?", "options": ["XY", "XX", "XO", "XXY"], "answer": "XX", "timeLimitSeconds": 20},
        {"id": "g9-tt-24", "text": "Hiện tượng cầu vồng xuất hiện sau cơn mưa là do hiện tượng quang học nào của ánh sáng mặt trời qua các giọt nước?", "options": ["Tán sắc ánh sáng", "Phản xạ ánh sáng", "Giao thoa ánh sáng", "Nhiễu xạ ánh sáng"], "answer": "Tán sắc ánh sáng", "timeLimitSeconds": 20},
        {"id": "g9-tt-25", "text": "Hiệp định Geneva về đình chỉ chiến sự ở Việt Nam và Đông Dương được ký kết vào năm nào?", "options": ["1945", "1954", "1973", "1975"], "answer": "1954", "timeLimitSeconds": 20},
        {"id": "g9-tt-26", "text": "Biết sin α = 3/5 (với 0 < α < 90°). Giá trị của cos α bằng bao nhiêu?", "options": ["4/5", "2/5", "1/5", "3/4"], "answer": "4/5", "timeLimitSeconds": 20},
        {"id": "g9-tt-27", "text": "Chất nào sau đây tham gia phản ứng tráng bạc (tác dụng với AgNO3 trong dung dịch NH3 sinh ra Ag)?", "options": ["Glucozơ", "Rượu etylic", "Axit axetic", "Benzen"], "answer": "Glucozơ", "timeLimitSeconds": 20},
        {"id": "g9-tt-28", "text": "Đột biến nào sau đây thuộc loại đột biến cấu trúc nhiễm sắc thể?", "options": ["Mất đoạn, lặp đoạn, đảo đoạn", "Tăng thêm 1 chiếc NST", "Mất 1 cặp nucleotit", "Đa bội thể"], "answer": "Mất đoạn, lặp đoạn, đảo đoạn", "timeLimitSeconds": 20},
        {"id": "g9-tt-29", "text": "Cây chè được trồng nhiều nhất ở vùng kinh tế nào của nước ta?", "options": ["Trung du và miền núi Bắc Bộ", "Đồng bằng sông Cửu Long", "Đông Nam Bộ", "Duyên hải Nam Trung Bộ"], "answer": "Trung du và miền núi Bắc Bộ", "timeLimitSeconds": 20},
        {"id": "g9-tt-30", "text": "Nhóm liên kết trong phân tử protein nối các đơn phân axit amin lại với nhau gọi là gì?", "options": ["Liên kết peptit", "Liên kết glicozit", "Liên kết este", "Liên kết photphodieste"], "answer": "Liên kết peptit", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g9-vd-10-4", "points": 10, "text": "Tâm đường tròn ngoại tiếp tam giác vuông nằm ở vị trí nào của tam giác?", "answer": "Trung điểm của cạnh huyền"},
        {"id": "g9-vd-10-5", "points": 10, "text": "Khí nào thoát ra khi cho canxi cacbua (đất đèn CaC2) tác dụng với nước?", "answer": "Khí axetilen (C2H2)"},
        {"id": "g9-vd-10-6", "points": 10, "text": "Dụng cụ quang học bổ trợ cho mắt gồm một thấu kính hội tụ có tiêu cự ngắn dùng để quan sát các vật nhỏ gọi là gì?", "answer": "Kính lúp"},
        {"id": "g9-vd-10-7", "points": 10, "text": "Tác phẩm 'Chiếc lược ngà' của Nguyễn Quang Sáng lấy bối cảnh cuộc kháng chiến chống đế quốc nào?", "answer": "Kháng chiến chống Mỹ"},
        {"id": "g9-vd-10-8", "points": 10, "text": "Bộ ba mã sao trên mARN mở đầu cho quá trình dịch mã tổng hợp protein có trình tự ba nucleotit nào?", "answer": "AUG"},
        {"id": "g9-vd-10-9", "points": 10, "text": "Tuyến đường sắt dài nhất Việt Nam nối liền Hà Nội và Thành phố Hồ Chí Minh có tên gọi là gì?", "answer": "Đường sắt Bắc - Nam (Đường sắt Thống Nhất)"},
        {"id": "g9-vd-10-10", "points": 10, "text": "Chiến lược chiến tranh nào của đế quốc Mỹ ở miền Nam (1961 - 1965) sử dụng công thức 'Quân đội Sài Gòn + Cố vấn và vũ khí Mỹ'?", "answer": "'Chiến tranh đặc biệt'"},
        {"id": "g9-vd-20-4", "points": 20, "text": "Tìm giá trị của tham số m để phương trình x^2 - 2x + m = 0 có nghiệm kép?", "answer": "m = 1"},
        {"id": "g9-vd-20-5", "points": 20, "text": "Đốt cháy hoàn toàn 4,48 lít khí metan (CH4) ở điều kiện tiêu chuẩn. Thể tích khí CO2 thu được ở cùng điều kiện là bao nhiêu lít?", "answer": "4,48 lít"},
        {"id": "g9-vd-20-6", "points": 20, "text": "Một máy biến áp có số vòng dây cuộn sơ cấp là 1000 vòng, cuộn thứ cấp là 200 vòng. Đặt vào cuộn sơ cấp hiệu điện thế xoay chiều 220V thì hiệu điện thế ở hai đầu cuộn thứ cấp là bao nhiêu Vôn?", "answer": "44 V"},
        {"id": "g9-vd-20-7", "points": 20, "text": "Bài thơ 'Ánh trăng' của Nguyễn Duy khép lại bằng lời nhắc nhở thiêng liêng về đạo lý sống nào của dân tộc?", "answer": "'Uống nước nhớ nguồn' (nghĩa tình thủy chung)"},
        {"id": "g9-vd-20-8", "points": 20, "text": "Trong tế bào nhân thực, quá trình phiên mã tổng hợp phân tử ARN diễn ra ở đâu?", "answer": "Trong nhân tế bào"},
        {"id": "g9-vd-20-9", "points": 20, "text": "Đặc khu kinh tế Vân Đồn thuộc địa phận tỉnh nào của vùng kinh tế trọng điểm Bắc Bộ?", "answer": "Quảng Ninh"},
        {"id": "g9-vd-20-10", "points": 20, "text": "Chiến dịch Hồ Chí Minh lịch sử bắt đầu vào ngày nào và toàn thắng vào ngày nào của năm 1975?", "answer": "Bắt đầu ngày 26/4 và toàn thắng ngày 30/4/1975"},
        {"id": "g9-vd-30-4", "points": 30, "text": "Cho tam giác ABC vuông tại A có đường cao AH. Biết AB = 15 cm, BH = 9 cm. Tính độ dài cạnh huyền BC?", "answer": "25 cm"},
        {"id": "g9-vd-30-5", "points": 30, "text": "Cho 10 gam hỗn hợp gồm bột đồng (Cu) và bột sắt (Fe) tác dụng với dung dịch HCl dư thu được 2,24 lít khí H2 ở đktc. Tính thành phần phần trăm theo khối lượng của Fe trong hỗn hợp (biết Fe = 56)?", "answer": "56%"},
        {"id": "g9-vd-30-6", "points": 30, "text": "Một vật sáng AB đặt vuông góc với trục chính của một thấu kính hội tụ có tiêu cự f = 20 cm, cách thấu kính một khoảng d = 30 cm. Khoảng cách d' từ ảnh đến thấu kính là bao nhiêu cm?", "answer": "60 cm"},
        {"id": "g9-vd-30-7", "points": 30, "text": "Một gen có chiều dài 4080 Å (Ăng-xtơ-rông). Tổng số nuclêôtit của gen đó là bao nhiêu?", "answer": "2400 nucleotit"},
        {"id": "g9-vd-30-8", "points": 30, "text": "Thắng cảnh danh thắng Tràng An được UNESCO công nhận là di sản thế giới hỗn hợp đầu tiên của Đông Nam Á thuộc tỉnh nào?", "answer": "Ninh Bình"},
        {"id": "g9-vd-30-9", "points": 30, "text": "Tác phẩm 'Bình Ngô đại cáo' được Nguyễn Trãi viết theo thể văn gì trong văn học trung đại Việt Nam?", "answer": "Thể Cáo (văn biền ngẫu)"},
        {"id": "g9-vd-30-10", "points": 30, "text": "Cuộc Tổng tiến công và nổi dậy Tết Mậu Thân năm 1968 của quân và dân ta đã buộc chính quyền Mỹ phải chấp nhận tuyên bố điều gì?", "answer": "Chấm dứt ném bom miền Bắc và chấp nhận ngồi vào bàn đàm phán Paris"}
    ]
}
