# -*- coding: utf-8 -*-
GRADE_6_DATA = {
    "warmup": [
        {"id": "g6-wu-6", "text": "Số nguyên tố nhỏ nhất và cũng là số nguyên tố chẵn duy nhất là số nào?", "answer": "Số 2"},
        {"id": "g6-wu-7", "text": "Bào quan nào được ví như 'nhà máy năng lượng' của tế bào nhân thực?", "answer": "Ty thể"},
        {"id": "g6-wu-8", "text": "Kim tự tháp Ai Cập cổ đại được xây dựng bên bờ con sông nổi tiếng nào?", "answer": "Sông Nin (Nile)"},
        {"id": "g6-wu-9", "text": "Tập hợp các số nguyên bao gồm số nguyên dương, số nguyên âm và số nào?", "answer": "Số 0"},
        {"id": "g6-wu-10", "text": "Biện pháp tu từ nào gọi tên sự vật, hiện tượng này bằng tên sự vật, hiện tượng khác có nét tương đồng?", "answer": "Ẩn dụ"},
        {"id": "g6-wu-11", "text": "Đơn vị đo lực trong hệ đo lường quốc tế (SI) được đặt theo tên nhà bác học nào?", "answer": "Niu-tơn (Newton, ký hiệu N)"},
        {"id": "g6-wu-12", "text": "Nhà nước Âu Lạc do ai đứng đầu sau khi hợp nhất Tây Âu và Lạc Việt?", "answer": "An Dương Vương (Thục Phán)"},
        {"id": "g6-wu-13", "text": "Trái Đất tự quay quanh trục của nó theo hướng từ tây sang đông hay từ đông sang tây?", "answer": "Từ tây sang đông"},
        {"id": "g6-wu-14", "text": "Số đối của số nguyên -15 là số nào?", "answer": "15"},
        {"id": "g6-wu-15", "text": "Chất khí nào chiếm khoảng 21% thể tích không khí và duy trì sự sống?", "answer": "Khí oxi (Oxygen)"},
        {"id": "g6-wu-16", "text": "Truyện 'Thạch Sanh' thuộc thể loại truyện dân gian nào?", "answer": "Truyện cổ tích"},
        {"id": "g6-wu-17", "text": "Lục giác đều có bao nhiêu trục đối xứng?", "answer": "6 trục đối xứng"},
        {"id": "g6-wu-18", "text": "Hệ thống chữ viết tượng hình cổ xưa nhất trên thế giới thuộc về nền văn minh nào?", "answer": "Văn minh Lưỡng Hà (chữ hình nêm) hoặc Ai Cập"},
        {"id": "g6-wu-19", "text": "Dụng cụ dùng để đo nhiệt độ trong đời sống và thí nghiệm là gì?", "answer": "Nhiệt kế"},
        {"id": "g6-wu-20", "text": "Vĩ tuyến đặc biệt có vĩ độ 0 độ chia Trái Đất thành hai bán cầu Bắc và Nam gọi là gì?", "answer": "Xích đạo"},
        {"id": "g6-wu-21", "text": "Ước chung lớn nhất của hai số nguyên tố cùng nhau bằng bao nhiêu?", "answer": "1"},
        {"id": "g6-wu-22", "text": "Trùng roi xanh và trùng giày là sinh vật đơn bào hay đa bào?", "answer": "Sinh vật đơn bào"},
        {"id": "g6-wu-23", "text": "Nhân vật truyền thuyết nào cưỡi ngựa sắt, mặc giáp sắt nhổ tre đánh tan giặc Ân?", "answer": "Thánh Gióng (Phù Đổng Thiên Vương)"},
        {"id": "g6-wu-24", "text": "Dạng năng lượng tích trữ trong một vật bị biến dạng đàn hồi như lò xo gọi là gì?", "answer": "Thế năng đàn hồi"},
        {"id": "g6-wu-25", "text": "Thành Cổ Loa có kiến trúc hình xoáy trôn ốc do vua nào cho xây dựng?", "answer": "An Dương Vương"},
        {"id": "g6-wu-26", "text": "Một tam giác đều có cạnh 7cm. Chu vi của tam giác đó là bao nhiêu?", "answer": "21 cm"},
        {"id": "g6-wu-27", "text": "Phần lớn nấm sinh sản bằng bộ phận gì nhỏ li ti?", "answer": "Bào tử"},
        {"id": "g6-wu-28", "text": "Biện pháp tu từ nào gọi tên sự vật, hiện tượng này bằng tên sự vật, hiện tượng khác có quan hệ gần gũi, đi đôi?", "answer": "Hoán dụ"},
        {"id": "g6-wu-29", "text": "Nhiệt độ nóng chảy của nước đá nguyên chất ở áp suất chuẩn là bao nhiêu độ C?", "answer": "0 độ C"},
        {"id": "g6-wu-30", "text": "Tầng khí quyển nào nằm sát mặt đất, là nơi diễn ra hầu hết các hiện tượng thời tiết như mưa, mây, bão?", "answer": "Tầng đối lưu"},
        {"id": "g6-wu-31", "text": "Kết quả của phép tính (-8) + (-12) bằng bao nhiêu?", "answer": "-20"},
        {"id": "g6-wu-32", "text": "Thực vật có hoa gồm hai cơ quan chính là cơ quan sinh dưỡng và cơ quan gì?", "answer": "Cơ quan sinh sản"},
        {"id": "g6-wu-33", "text": "Nền văn minh Ấn Độ cổ đại gắn liền với hai con sông lớn nào?", "answer": "Sông Ấn (Indus) và sông Hằng (Ganges)"},
        {"id": "g6-wu-34", "text": "Đại lượng vật lý nào đặc trưng cho mức độ tác dụng lực lên một đơn vị diện tích bề mặt?", "answer": "Áp suất"},
        {"id": "g6-wu-35", "text": "Kinh tuyến gốc đi qua đài thiên văn Greenwich ở thủ đô Luân Đôn có kinh độ bao nhiêu?", "answer": "0 độ"},
        {"id": "g6-wu-36", "text": "Phân số nghịch đảo của phân số -3/7 là phân số nào?", "answer": "-7/3"},
        {"id": "g6-wu-37", "text": "Vi khuẩn thuộc nhóm tế bào nhân sơ hay tế bào nhân thực?", "answer": "Tế bào nhân sơ"},
        {"id": "g6-wu-38", "text": "Trong tiếng Việt, cụm từ cố định có ý nghĩa hoàn chỉnh và bóng bẩy như 'Cưỡi ngựa xem hoa' gọi là gì?", "answer": "Thành ngữ"},
        {"id": "g6-wu-39", "text": "Quá trình nước chuyển trực tiếp từ thể rắn sang thể khí gọi là hiện tượng gì?", "answer": "Thăng hoa"},
        {"id": "g6-wu-40", "text": "Trống đồng Đông Sơn là hiện vật tiêu biểu cho nền văn hóa khảo cổ học nào của người Việt cổ?", "answer": "Văn hóa Đông Sơn"}
    ],
    "acceleration": [
        {"id": "g6-tt-6", "text": "Tổng các số nguyên x thỏa mãn -4 < x < 5 bằng bao nhiêu?", "options": ["4", "0", "9", "-4"], "answer": "4", "timeLimitSeconds": 20},
        {"id": "g6-tt-7", "text": "Bào quan nào CHỈ CÓ ở tế bào thực vật mà KHÔNG CÓ ở tế bào động vật?", "options": ["Ty thể", "Lục lạp", "Ribosome", "Nhân tế bào"], "answer": "Lục lạp", "timeLimitSeconds": 20},
        {"id": "g6-tt-8", "text": "Nhà nước phương Tây cổ đại nào được coi là quê hương của chế độ dân chủ và thế vận hội Olympic?", "options": ["La Mã", "Hy Lạp", "Lưỡng Hà", "Ai Cập"], "answer": "Hy Lạp", "timeLimitSeconds": 20},
        {"id": "g6-tt-9", "text": "Một quả táo rơi từ trên cành cây xuống đất là do tác dụng của lực nào?", "options": ["Lực ma sát", "Lực hút của Trái Đất (Trọng lực)", "Lực đẩy Archimedes", "Lực từ"], "answer": "Lực hút của Trái Đất (Trọng lực)", "timeLimitSeconds": 20},
        {"id": "g6-tt-10", "text": "Hiện tượng ngày đêm luân phiên trên Trái Đất là do:", "options": ["Trái Đất quay quanh Mặt Trời", "Trái Đất tự quay quanh trục của nó", "Mặt Trời quay quanh Trái Đất", "Mặt Trăng che khuất Mặt Trời"], "answer": "Trái Đất tự quay quanh trục của nó", "timeLimitSeconds": 20},
        {"id": "g6-tt-11", "text": "Số nào sau đây là số nguyên tố?", "options": ["9", "15", "21", "29"], "answer": "29", "timeLimitSeconds": 20},
        {"id": "g6-tt-12", "text": "Từ ngữ nào là từ láy tượng thanh?", "options": ["Róc rách", "Xanh xao", "Mênh mông", "Nhỏ nhắn"], "answer": "Róc rách", "timeLimitSeconds": 20},
        {"id": "g6-tt-13", "text": "Trong thang nhiệt độ Celsius (°C), nhiệt độ đông đặc của nước là bao nhiêu?", "options": ["0 °C", "100 °C", "32 °C", "273 °C"], "answer": "0 °C", "timeLimitSeconds": 20},
        {"id": "g6-tt-14", "text": "Người tối cổ đã biết chế tạo công cụ lao động đầu tiên bằng chất liệu gì?", "options": ["Đồng thau", "Sắt", "Đá", "Gốm"], "answer": "Đá", "timeLimitSeconds": 20},
        {"id": "g6-tt-15", "text": "Hình bình hành có diện tích 48 cm2, đáy dài 8 cm. Chiều cao tương ứng là bao nhiêu?", "options": ["6 cm", "12 cm", "8 cm", "4 cm"], "answer": "6 cm", "timeLimitSeconds": 20},
        {"id": "g6-tt-16", "text": "Giới sinh vật nào sau đây KHÔNG THỂ tự dưỡng quang hợp?", "options": ["Thực vật", "Giới Nấm", "Tảo đơn bào", "Vi khuẩn lam"], "answer": "Giới Nấm", "timeLimitSeconds": 20},
        {"id": "g6-tt-17", "text": "Lực cản trở chuyển động của một vật khi nó trượt trên bề mặt vật khác gọi là lực gì?", "options": ["Lực hấp dẫn", "Lực ma sát trượt", "Lực đàn hồi", "Lực nâng"], "answer": "Lực ma sát trượt", "timeLimitSeconds": 20},
        {"id": "g6-tt-18", "text": "Khu vực nằm giữa hai chí tuyến Bắc và Nam được gọi là đới khí hậu nào?", "options": ["Đới nóng (Nhiệt đới)", "Đới ôn hòa (Ôn đới)", "Đới lạnh (Hàn đới)", "Cận cực"], "answer": "Đới nóng (Nhiệt đới)", "timeLimitSeconds": 20},
        {"id": "g6-tt-19", "text": "Kết quả của phép tính (-5) . (-6) là bao nhiêu?", "options": ["-30", "30", "11", "-11"], "answer": "30", "timeLimitSeconds": 20},
        {"id": "g6-tt-20", "text": "Vạn Lý Trường Thành là công trình kiến trúc phòng thủ nổi tiếng của quốc gia cổ đại nào?", "options": ["Ấn Độ", "Trung Quốc", "Ai Cập", "Hy Lạp"], "answer": "Trung Quốc", "timeLimitSeconds": 20},
        {"id": "g6-tt-21", "text": "Vật nào sau đây DẪN NHIỆT kém nhất (cách nhiệt tốt)?", "options": ["Đồng", "Nhôm", "Thủy tinh", "Xốp"], "answer": "Xốp", "timeLimitSeconds": 20},
        {"id": "g6-tt-22", "text": "Trong câu 'Người Cha mái tóc bạc / Đốt lửa cho anh nằm', từ 'Người Cha' sử dụng phép tu từ nào?", "options": ["So sánh", "Ẩn dụ", "Hoán dụ", "Nhân hóa"], "answer": "Ẩn dụ", "timeLimitSeconds": 20},
        {"id": "g6-tt-23", "text": "Hình thoi có độ dài hai đường chéo lần lượt là 10 cm và 14 cm. Diện tích của nó là:", "options": ["70 cm2", "140 cm2", "35 cm2", "48 cm2"], "answer": "70 cm2", "timeLimitSeconds": 20},
        {"id": "g6-tt-24", "text": "Đơn vị cơ bản cấu tạo nên mọi cơ thể sống là gì?", "options": ["Mô", "Cơ quan", "Tế bào", "Hệ cơ quan"], "answer": "Tế bào", "timeLimitSeconds": 20},
        {"id": "g6-tt-25", "text": "Bão nhiệt đới ở bán cầu Bắc có chiều xoáy không khí như thế nào?", "options": ["Cùng chiều kim đồng hồ", "Ngược chiều kim đồng hồ", "Xoáy thẳng đứng", "Không có chiều xoáy"], "answer": "Ngược chiều kim đồng hồ", "timeLimitSeconds": 20},
        {"id": "g6-tt-26", "text": "Bộ luật thành văn cổ xưa nhất của nhân loại còn bảo tồn nguyên vẹn là bộ luật nào?", "options": ["Luật Hammurabi", "Luật Hồng Đức", "Luật 12 bảng La Mã", "Luật Gia Long"], "answer": "Luật Hammurabi", "timeLimitSeconds": 20},
        {"id": "g6-tt-27", "text": "Bội chung nhỏ nhất của hai số 12 và 18 là bao nhiêu?", "options": ["36", "72", "18", "6"], "answer": "36", "timeLimitSeconds": 20},
        {"id": "g6-tt-28", "text": "Động vật nào sau đây thuộc nhóm ĐỘNG VẬT KHÔNG XƯƠNG SỐNG?", "options": ["Cá rô phi", "Chim bồ câu", "Mực ống", "Ếch đồng"], "answer": "Mực ống", "timeLimitSeconds": 20},
        {"id": "g6-tt-29", "text": "Khi kéo một gàu nước từ giếng lên, ta đã sử dụng loại máy cơ đơn giản nào?", "options": ["Mặt phẳng nghiêng", "Đòn bẩy", "Ròng rọc cố định", "Nêm"], "answer": "Ròng rọc cố định", "timeLimitSeconds": 20},
        {"id": "g6-tt-30", "text": "Đại dương nào có diện tích nhỏ nhất trên Trái Đất?", "options": ["Thái Bình Dương", "Đại Tây Dương", "Ấn Độ Dương", "Bắc Băng Dương"], "answer": "Bắc Băng Dương", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g6-vd-10-4", "points": 10, "text": "Số nguyên âm biểu diễn độ cao dưới mực nước biển hay trên mực nước biển?", "answer": "Dưới mực nước biển"},
        {"id": "g6-vd-10-5", "points": 10, "text": "Tác phẩm cổ tích thần kỳ nào của Việt Nam kể về cuộc đấu tranh thiện ác giữa hai chị em cùng cha khác mẹ?", "answer": "Tấm Cám"},
        {"id": "g6-vd-10-6", "points": 10, "text": "Chất lỏng màu đỏ lưu thông trong hệ tuần hoàn của người và động vật có xương sống gọi là gì?", "answer": "Máu"},
        {"id": "g6-vd-10-7", "points": 10, "text": "Khoảng cách từ tâm Trái Đất đến xích đạo dài hơn hay ngắn hơn khoảng cách từ tâm đến hai cực?", "answer": "Dài hơn (Trái Đất phình ở xích đạo)"},
        {"id": "g6-vd-10-8", "points": 10, "text": "Lấy một ví dụ về nguồn năng lượng không tái tạo phổ biến trong đời sống?", "answer": "Than đá (hoặc dầu mỏ, khí đốt)"},
        {"id": "g6-vd-10-9", "points": 10, "text": "Tìm số tự nhiên x biết: 2^x = 16?", "answer": "x = 4"},
        {"id": "g6-vd-10-10", "points": 10, "text": "Kinh đô đầu tiên của nhà nước Văn Lang đóng ở vùng đất thuộc tỉnh nào ngày nay?", "answer": "Phú Thọ (Phong Châu)"},
        {"id": "g6-vd-20-4", "points": 20, "text": "Tìm ước chung lớn nhất của hai số 48 và 72?", "answer": "24"},
        {"id": "g6-vd-20-5", "points": 20, "text": "Người phát minh ra định luật vạn vật hấp dẫn khi nhìn thấy quả táo rơi là nhà bác học nào?", "answer": "Isaac Newton"},
        {"id": "g6-vd-20-6", "points": 20, "text": "Nhà nước cổ đại nào ở Lưỡng Hà đã sáng tạo ra hệ thống đếm cơ số 60 mà nay chúng ta vẫn dùng để chia giờ và phút?", "answer": "Người Sumer (Lưỡng Hà)"},
        {"id": "g6-vd-20-7", "points": 20, "text": "Nếu nhiệt độ lúc sáng sớm là -3 °C và buổi trưa tăng thêm 8 °C thì nhiệt độ buổi trưa là bao nhiêu độ C?", "answer": "5 °C"},
        {"id": "g6-vd-20-8", "points": 20, "text": "Bài thơ 'Đêm nay Bác không ngủ' do nhà thơ nào sáng tác?", "answer": "Minh Huệ"},
        {"id": "g6-vd-20-9", "points": 20, "text": "Bào quan nào chứa vật chất di truyền ADN điều khiển mọi hoạt động của tế bào nhân thực?", "answer": "Nhân tế bào"},
        {"id": "g6-vd-20-10", "points": 20, "text": "Trên bản đồ tỉ lệ 1 : 1 000 000, khoảng cách giữa hai thành phố đo được 5 cm thì khoảng cách thực tế ngoài đời là bao nhiêu km?", "answer": "50 km"},
        {"id": "g6-vd-30-4", "points": 30, "text": "Tìm số tự nhiên nhỏ nhất chia cho 3 dư 2, chia cho 5 dư 4 và chia cho 7 dư 6?", "answer": "104"},
        {"id": "g6-vd-30-5", "points": 30, "text": "Một vật có khối lượng 500g được treo vào lực kế thì kim lực kế chỉ giá trị xấp xỉ bao nhiêu Niu-tơn?", "answer": "5 N (lấy g = 10 m/s2)"},
        {"id": "g6-vd-30-6", "points": 30, "text": "Hai vị tướng nữ anh hùng nào cưỡi voi phất cờ khởi nghĩa đánh tan quân đô hộ nhà Đông Hán vào năm 40 sau Công nguyên?", "answer": "Hai Bà Trưng (Trưng Trắc, Trưng Nhị)"},
        {"id": "g6-vd-30-7", "points": 30, "text": "Hiện tượng thủy triều lên xuống hằng ngày ở các bờ biển chủ yếu do lực hấp dẫn của thiên thể nào đối với Trái Đất?", "answer": "Mặt Trăng (và Mặt Trời)"},
        {"id": "g6-vd-30-8", "points": 30, "text": "Chứng minh rằng với mọi số tự nhiên n thì (n + 1) và (2n + 3) là hai số nguyên tố cùng nhau. Khi đó ước chung lớn nhất của chúng bằng bao nhiêu?", "answer": "1"},
        {"id": "g6-vd-30-9", "points": 30, "text": "Tác phẩm văn học dịch nổi tiếng của nhà văn Pháp Antoine de Saint-Exupéry kể về cuộc hành trình kỳ lạ của một cậu bé tóc vàng giữa các tiểu hành tinh tên là gì?", "answer": "Hoàng tử bé (Le Petit Prince)"},
        {"id": "g6-vd-30-10", "points": 30, "text": "Vì sao khi lặn xuống sâu dưới đáy biển, người thợ lặn phải mặc bộ đồ bảo hộ chịu lực đặc biệt?", "answer": "Vì áp suất chất lỏng tăng dần theo độ sâu"}
    ]
}
