# -*- coding: utf-8 -*-
GRADE_8_DATA = {
    "warmup": [
        {"id": "g8-wu-6", "text": "Hằng đẳng thức đáng nhớ (A + B)^2 khai triển thành biểu thức nào?", "answer": "A^2 + 2AB + B^2"},
        {"id": "g8-wu-7", "text": "Đơn vị đo khối lượng mol của một chất trong hóa học là gì?", "answer": "g/mol (gam trên mol)"},
        {"id": "g8-wu-8", "text": "Lực đẩy do chất lỏng tác dụng lên một vật nhúng chìm trong nó được đặt theo tên nhà bác học cổ Hy Lạp nào?", "answer": "Archimedes (Ác-si-mét)"},
        {"id": "g8-wu-9", "text": "Truyện ngắn hiện thực nổi tiếng 'Lão Hạc' viết về số phận người nông dân nghèo trước cách mạng là của nhà văn nào?", "answer": "Nam Cao"},
        {"id": "g8-wu-10", "text": "Quần xã sinh vật kết hợp với sinh cảnh (môi trường vô sinh) tạo thành cấp độ tổ chức sống nào?", "answer": "Hệ sinh thái"},
        {"id": "g8-wu-11", "text": "Định lý hình học nào khẳng định một đường thẳng song song với một cạnh của tam giác và cắt hai cạnh còn lại thì định ra trên hai cạnh đó những đoạn thẳng tương ứng tỉ lệ?", "answer": "Định lý Thales (Ta-lét)"},
        {"id": "g8-wu-12", "text": "Chất chỉ thị màu nào thường dùng để nhận biết dung dịch axit bằng cách chuyển sang màu đỏ?", "answer": "Quỳ tím"},
        {"id": "g8-wu-13", "text": "Khởi nghĩa Hương Khê - đỉnh cao của phong trào Cần Vương do ai lãnh đạo?", "answer": "Phan Đình Phùng"},
        {"id": "g8-wu-14", "text": "Cơ quan nào trong hệ tiêu hóa của người tiết ra mật để giúp nhũ tương hóa chất béo?", "answer": "Gan"},
        {"id": "g8-wu-15", "text": "Một mol chất khí ở điều kiện chuẩn (25 độ C, 1 bar) chiếm thể tích xấp xỉ bằng bao nhiêu lít?", "answer": "24,79 lít"},
        {"id": "g8-wu-16", "text": "Tứ giác có hai đường chéo vuông góc với nhau tại trung điểm của mỗi đường là hình gì?", "answer": "Hình thoi"},
        {"id": "g8-wu-17", "text": "Tác phẩm 'Chiếc lá cuối cùng' là kiệt tác truyện ngắn của nhà văn nổi tiếng người Mỹ nào?", "answer": "O. Henry (Ô Hen-ri)"},
        {"id": "g8-wu-18", "text": "Khối lượng riêng của nước nguyên chất ở điều kiện thường là bao nhiêu kg/m3?", "answer": "1000 kg/m3"},
        {"id": "g8-wu-19", "text": "Khí hậu nước ta mang tính chất nhiệt đới gió mùa ẩm với hai mùa gió chính là gió mùa mùa đông và gió mùa gì?", "answer": "Gió mùa mùa hạ"},
        {"id": "g8-wu-20", "text": "Số Avogadro (N) biểu thị số hạt có trong 1 mol chất có giá trị xấp xỉ bằng bao nhiêu?", "answer": "6,022 x 10^23"},
        {"id": "g8-wu-21", "text": "Đoạn trích 'Tức nước vỡ bờ' với hình tượng chị Dậu quật ngã cai lệ trích từ tiểu thuyết nào của Ngô Tất Tố?", "answer": "Tắt đèn"},
        {"id": "g8-wu-22", "text": "Công thức tính áp suất chất lỏng p tại độ sâu h là gì?", "answer": "p = d x h (hoặc p = r x g x h)"},
        {"id": "g8-wu-23", "text": "Hệ tuần hoàn ở người có bao nhiêu vòng tuần hoàn chính?", "answer": "2 vòng (vòng tuần hoàn lớn và nhỏ)"},
        {"id": "g8-wu-24", "text": "Hình chữ nhật có hai cạnh kề bằng nhau là hình gì?", "answer": "Hình vuông"},
        {"id": "g8-wu-25", "text": "Cuộc Cách mạng tư sản Pháp năm 1789 bùng nổ với sự kiện quần chúng nhân dân tấn công phá ngục nào?", "answer": "Ngục Bastille (Ba-xti)"},
        {"id": "g8-wu-26", "text": "Phản ứng giữa axit và bazơ tạo thành muối và nước được gọi là phản ứng gì?", "answer": "Phản ứng trung hòa"},
        {"id": "g8-wu-27", "text": "Vùng mỏ than đá lớn nhất và chất lượng tốt nhất ở nước ta tập trung ở tỉnh nào?", "answer": "Quảng Ninh"},
        {"id": "g8-wu-28", "text": "Hình bình hành có một góc vuông trở thành hình gì?", "answer": "Hình chữ nhật"},
        {"id": "g8-wu-29", "text": "Kháng thể do tế bào lympho nào của hệ miễn dịch tiết ra để tiêu diệt kháng nguyên?", "answer": "Tế bào lympho B"},
        {"id": "g8-wu-30", "text": "Nhà bác học người Scotland nào đã phát minh ra máy hơi nước vào năm 1784 thúc đẩy cách mạng công nghiệp?", "answer": "James Watt"},
        {"id": "g8-wu-31", "text": "Hai tam giác đồng dạng với nhau theo tỉ số k thì diện tích của chúng tỉ lệ với nhau theo tỉ số nào?", "answer": "k^2 (k bình phương)"},
        {"id": "g8-wu-32", "text": "Trong câu thơ 'Bác bảo sao, nghe nấy', từ 'nấy' thuộc từ loại nào?", "answer": "Đại từ"},
        {"id": "g8-wu-33", "text": "Kim loại nào tác dụng mãnh liệt với nước ở nhiệt độ thường tạo thành dung dịch kiềm và giải phóng khí hiđro?", "answer": "Natri (hoặc Kali, Canxi)"},
        {"id": "g8-wu-34", "text": "Áp suất khí quyển ở ngang mực nước biển xấp xỉ bằng áp suất của một cột thủy ngân cao bao nhiêu milimét?", "answer": "760 mmHg"},
        {"id": "g8-wu-35", "text": "Con sông nào ở miền Trung có dòng chảy hướng từ đông sang tây sang nước bạn Lào?", "answer": "Sông Xê Xan hoặc Sông Sêrêpôk"},
        {"id": "g8-wu-36", "text": "Phương trình ax + b = 0 có nghiệm duy nhất khi và chỉ khi hệ số a như thế nào?", "answer": "a khác 0"},
        {"id": "g8-wu-37", "text": "Hormone insulin do tuyến nội tiết nào của cơ thể tiết ra để điều hòa lượng đường huyết?", "answer": "Tuyến tụy"},
        {"id": "g8-wu-38", "text": "Phong trào khởi nghĩa nông dân kéo dài gần 30 năm (1884 - 1913) ở vùng núi Bắc Giang do Hoàng Hoa Thám lãnh đạo tên là gì?", "answer": "Khởi nghĩa Yên Thế"},
        {"id": "g8-wu-39", "text": "Dung dịch có độ pH nhỏ hơn 7 thì mang tính chất gì?", "answer": "Tính axit"},
        {"id": "g8-wu-40", "text": "Thiết bị dùng để đo cường độ dòng điện trong mạch điện tên là gì?", "answer": "Ampe kế (Ammeter)"}
    ],
    "acceleration": [
        {"id": "g8-tt-6", "text": "Khai triển hằng đẳng thức A^3 - B^3 bằng biểu thức nào sau đây?", "options": ["(A - B)(A^2 + AB + B^2)", "(A - B)(A^2 - AB + B^2)", "(A + B)(A^2 - AB + B^2)", "(A - B)^3"], "answer": "(A - B)(A^2 + AB + B^2)", "timeLimitSeconds": 20},
        {"id": "g8-tt-7", "text": "Khí nào sau đây NẶNG HƠN không khí (M > 29)?", "options": ["Khí Oxi (O2)", "Khí Metan (CH4)", "Khí Hiđro (H2)", "Khí Amoniac (NH3)"], "answer": "Khí Oxi (O2)", "timeLimitSeconds": 20},
        {"id": "g8-tt-8", "text": "Một vật chìm hoàn toàn trong nước chịu lực đẩy Archimedes là 20 N. Thể tích của vật đó là bao nhiêu (biết d_nước = 10 000 N/m3)?", "options": ["0,002 m3", "0,02 m3", "0,2 m3", "2 m3"], "answer": "0,002 m3", "timeLimitSeconds": 20},
        {"id": "g8-tt-9", "text": "Nhà văn Nga nào là tác giả của các truyện ngắn hiện thực sâu sắc như 'Người trong bao', 'Con kỳ nhông'?", "options": ["Lev Tolstoy", "Anton Chekhov", "Maxim Gorky", "Pushkin"], "answer": "Anton Chekhov", "timeLimitSeconds": 20},
        {"id": "g8-tt-10", "text": "Cơ quan nào trong cơ thể người là trung khu điều hòa thân nhiệt?", "options": ["Hành não", "Vùng dưới đồi (Não trung gian)", "Tiểu não", "Tủy sống"], "answer": "Vùng dưới đồi (Não trung gian)", "timeLimitSeconds": 20},
        {"id": "g8-tt-11", "text": "Nghiệm của phương trình: 3x - 12 = 0 là:", "options": ["x = 3", "x = 4", "x = -4", "x = 12"], "answer": "x = 4", "timeLimitSeconds": 20},
        {"id": "g8-tt-12", "text": "Chiếu chỉ Cần Vương (1885) kêu gọi văn thân, sĩ phu và nhân dân giúp vua cứu nước được ban hành dưới danh nghĩa vị vua nào?", "options": ["Vua Hàm Nghi", "Vua Duy Tân", "Vua Thành Thái", "Vua Tự Đức"], "answer": "Vua Hàm Nghi", "timeLimitSeconds": 20},
        {"id": "g8-tt-13", "text": "Chất nào sau đây là BAZƠ TAN TRONG NƯỚC (Kiềm)?", "options": ["Cu(OH)2", "NaOH", "Fe(OH)3", "Al(OH)3"], "answer": "NaOH", "timeLimitSeconds": 20},
        {"id": "g8-tt-14", "text": "Hình thang cân là hình thang có:", "options": ["Hai góc kề một đáy bằng nhau", "Hai cạnh bên song song", "Hai đường chéo vuông góc", "Hai đáy bằng nhau"], "answer": "Hai góc kề một đáy bằng nhau", "timeLimitSeconds": 20},
        {"id": "g8-tt-15", "text": "Gió mùa Tây Nam thổi vào mùa hạ nước ta có nguồn gốc từ đâu?", "options": ["Áp cao cận chí tuyến Nam bán cầu", "Áp cao Siberia", "Áp cao chí tuyến Tây Thái Bình Dương", "Vùng cực Bắc"], "answer": "Áp cao cận chí tuyến Nam bán cầu", "timeLimitSeconds": 20},
        {"id": "g8-tt-16", "text": "Khối lượng của 0,5 mol khí CO2 là bao nhiêu gam?", "options": ["22 gam", "44 gam", "28 gam", "14 gam"], "answer": "22 gam", "timeLimitSeconds": 20},
        {"id": "g8-tt-17", "text": "Nhóm máu nào được gọi là 'nhóm máu chuyên cho' vì có thể truyền cho tất cả các nhóm máu khác?", "options": ["Nhóm máu A", "Nhóm máu B", "Nhóm máu AB", "Nhóm máu O"], "answer": "Nhóm máu O", "timeLimitSeconds": 20},
        {"id": "g8-tt-18", "text": "Trong câu 'Trời ơi, nóng quá!', từ 'Trời ơi' thuộc loại từ nào?", "options": ["Trợ từ", "Thán từ", "Tình thái từ", "Phó từ"], "answer": "Thán từ", "timeLimitSeconds": 20},
        {"id": "g8-tt-19", "text": "Công cụ nào sau đây là ứng dụng của ĐÒN BẨY loại 1 (điểm tựa ở giữa)?", "options": ["Chiếc kéo cắt giấy", "Cái mở nắp chai", "Chiếc xe cút kít", "Nhíp gắp"], "answer": "Chiếc kéo cắt giấy", "timeLimitSeconds": 20},
        {"id": "g8-tt-20", "text": "Một hình chóp tam giác đều có diện tích đáy là 15 cm2, chiều cao là 6 cm. Thể tích của nó là:", "options": ["90 cm3", "45 cm3", "30 cm3", "15 cm3"], "answer": "30 cm3", "timeLimitSeconds": 20},
        {"id": "g8-tt-21", "text": "Quốc gia nào được mệnh danh là 'Xưởng xưởng của thế giới' trong cuộc cách mạng công nghiệp thế kỷ XIX?", "options": ["Pháp", "Đức", "Nước Anh", "Hoa Kỳ"], "answer": "Nước Anh", "timeLimitSeconds": 20},
        {"id": "g8-tt-22", "text": "Axit nào có nhiều trong dịch vị dạ dày của con người giúp tiêu hóa thức ăn và diệt khuẩn?", "options": ["H2SO4", "HNO3", "HCl", "CH3COOH"], "answer": "HCl", "timeLimitSeconds": 20},
        {"id": "g8-tt-23", "text": "Nhịp tim trung bình của một người trưởng thành khỏe mạnh lúc nghỉ ngơi khoảng bao nhiêu nhịp một phút?", "options": ["40 - 50", "70 - 80", "110 - 120", "140 - 150"], "answer": "70 - 80", "timeLimitSeconds": 20},
        {"id": "g8-tt-24", "text": "Cho tam giác ABC có AD là đường phân giác trong của góc A (D thuộc BC). Hệ thức nào sau đây ĐÚNG?", "options": ["DB / DC = AB / AC", "DB / DC = AC / AB", "DB / AB = DC / AC", "DB . DC = AB . AC"], "answer": "DB / DC = AB / AC", "timeLimitSeconds": 20},
        {"id": "g8-tt-25", "text": "Khoáng sản bô-xít dùng để luyện nhôm phân bố tập trung nhiều nhất ở vùng nào nước ta?", "options": ["Tây Nguyên", "Trung du Bắc Bộ", "Bắc Trung Bộ", "Đông Nam Bộ"], "answer": "Tây Nguyên", "timeLimitSeconds": 20},
        {"id": "g8-tt-26", "text": "Hòa tan 20g muối NaCl vào 80g nước. Nồng độ phần trăm (C%) của dung dịch thu được là:", "options": ["20%", "25%", "15%", "10%"], "answer": "20%", "timeLimitSeconds": 20},
        {"id": "g8-tt-27", "text": "Đơn vị chức năng cấu tạo nên hệ thần kinh của người là tế bào gì?", "options": ["Tế bào cơ", "Tế bào thần kinh (Nơron)", "Tế bào biểu mô", "Tế bào hồng cầu"], "answer": "Tế bào thần kinh (Nơron)", "timeLimitSeconds": 20},
        {"id": "g8-tt-28", "text": "Vật liệu kim loại nào sau đây bị nam châm hút mạnh?", "options": ["Đồng", "Nhôm", "Sắt", "Bạc"], "answer": "Sắt", "timeLimitSeconds": 20},
        {"id": "g8-tt-29", "text": "Bài thơ trào phúng 'Đất Vị Hoàng' phản ánh sự đổi thay suy đồi của xã hội nửa phong kiến do thi sĩ nào sáng tác?", "options": ["Tú Xương (Trần Tế Xương)", "Nguyễn Khuyến", "Nguyễn Du", "Cao Bá Quát"], "answer": "Tú Xương (Trần Tế Xương)", "timeLimitSeconds": 20},
        {"id": "g8-tt-30", "text": "Đường trung bình của một tam giác thì song song với cạnh thứ ba và bằng bao nhiêu phần cạnh đó?", "options": ["Bằng 1/3", "Bằng 1/2", "Bằng 2/3", "Bằng 1/4"], "answer": "Bằng 1/2", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g8-vd-10-4", "points": 10, "text": "Tập nghiệm của phương trình x^2 - 9 = 0 gồm những số nào?", "answer": "x = 3 và x = -3"},
        {"id": "g8-vd-10-5", "points": 10, "text": "Kim loại nào được người Việt cổ đúc nên trống đồng Đông Sơn và thạp đồng?", "answer": "Đồng (hợp kim đồng thau)"},
        {"id": "g8-vd-10-6", "points": 10, "text": "Khí nào thoát ra khi cho mẩu kẽm (Zn) tác dụng với dung dịch axit clohiđric (HCl)?", "answer": "Khí hiđro (H2)"},
        {"id": "g8-vd-10-7", "points": 10, "text": "Hệ cơ quan nào trong cơ thể thực hiện chức năng lọc máu và bài tiết các chất thải chuyển hóa qua nước tiểu?", "answer": "Hệ bài tiết (Thận)"},
        {"id": "g8-vd-10-8", "points": 10, "text": "Một hình chữ nhật có độ dài hai đường chéo có tính chất gì?", "answer": "Bằng nhau và cắt nhau tại trung điểm mỗi đường"},
        {"id": "g8-vd-10-9", "points": 10, "text": "Tác phẩm 'Hịch tướng sĩ' được Trần Quốc Tuấn viết vào trước cuộc kháng chiến chống quân Mông-Nguyên lần thứ mấy?", "answer": "Lần thứ hai (năm 1285)"},
        {"id": "g8-vd-10-10", "points": 10, "text": "Dụng cụ đo áp suất chất lỏng và khí có nguyên lý hoạt động dựa trên cấu tạo bình gì?", "answer": "Bình thông nhau"},
        {"id": "g8-vd-20-4", "points": 20, "text": "Tính khối lượng kết tủa trắng thu được khi cho dung dịch chứa 0,1 mol BaCl2 phản ứng hoàn toàn với dung dịch Na2SO4 dư (biết M BaSO4 = 233)?", "answer": "23,3 gam"},
        {"id": "g8-vd-20-5", "points": 20, "text": "Người anh hùng dân tộc nào đã lãnh đạo nghĩa quân nông dân lập căn cứ Bãi Sậy chống thực dân Pháp?", "answer": "Nguyễn Thiện Thuật"},
        {"id": "g8-vd-20-6", "points": 20, "text": "Một đòn bẩy có trục quay ở giữa. Đặt một vật có trọng lượng 100 N cách trục quay 20 cm. Hỏi cần tác dụng một lực F bằng bao nhiêu ở đầu kia cách trục quay 50 cm để đòn bẩy cân bằng?", "answer": "40 N"},
        {"id": "g8-vd-20-7", "points": 20, "text": "Rút gọn phân thức đại số: (x^2 - 4) / (x + 2) với x khác -2 ta được kết quả là gì?", "answer": "x - 2"},
        {"id": "g8-vd-20-8", "points": 20, "text": "Vòng tuần hoàn lớn ở người bắt đầu đẩy máu đỏ tươi giàu oxi từ ngăn nào của tim đi nuôi cơ thể?", "answer": "Tâm thất trái"},
        {"id": "g8-vd-20-9", "points": 20, "text": "Đỉnh núi Phan Xi Păng thuộc dãy núi Hoàng Liên Sơn cao chính xác là bao nhiêu mét so với mực nước biển theo số liệu chuẩn?", "answer": "3143 mét (hoặc 3147 mét theo mốc mới 2019)"},
        {"id": "g8-vd-20-10", "points": 20, "text": "Trong lịch sử triết học và chính trị thế giới, bản 'Tuyên ngôn của Đảng Cộng sản' (1848) do ai cùng với Friedrich Engels soạn thảo?", "answer": "Karl Marx (Các Mác)"},
        {"id": "g8-vd-30-4", "points": 30, "text": "Cho biểu thức A = x^2 - 4x + 7. Tìm giá trị nhỏ nhất của biểu thức A và giá trị của x tương ứng?", "answer": "Giá trị nhỏ nhất là 3 khi x = 2"},
        {"id": "g8-vd-30-5", "points": 30, "text": "Để hòa tan hoàn toàn 8 gam oxit đồng CuO cần dùng vừa đủ bao nhiêu gam dung dịch H2SO4 9,8% (biết Cu=64, O=16, H=1, S=32)?", "answer": "100 gam"},
        {"id": "g8-vd-30-6", "points": 30, "text": "Bức tượng Nữ thần Tự do nổi tiếng ở cảng New York là món quà mà nhân dân quốc gia nào đã trao tặng cho nước Mỹ vào cuối thế kỷ XIX?", "answer": "Nước Pháp"},
        {"id": "g8-vd-30-7", "points": 30, "text": "Hiện tượng cận thị ở mắt người là do trục mắt quá dài hoặc thể thủy tinh quá phồng. Để khắc phục tật cận thị ta phải đeo kính có thấu kính thuộc loại nào?", "answer": "Thấu kính phân kỳ"},
        {"id": "g8-vd-30-8", "points": 30, "text": "Cho tam giác ABC vuông tại A có đường cao AH. Biết BH = 4 cm, CH = 9 cm. Tính độ dài đường cao AH?", "answer": "6 cm"},
        {"id": "g8-vd-30-9", "points": 30, "text": "Loại đất nào chiếm diện tích lớn nhất trong các nhóm đất ở vùng đồi núi của nước ta, rất thích hợp trồng cây công nghiệp lâu năm?", "answer": "Đất feralit"},
        {"id": "g8-vd-30-10", "points": 30, "text": "Đại hội nào của Hiệp hội Công nhân Quốc tế (Quốc tế thứ nhất) đã thông qua nghị quyết về ngày làm việc 8 giờ?", "answer": "Đại hội Geneva (1866) hoặc Quốc tế II thông qua Ngày Quốc tế Lao động 1/5"}
    ]
}
