# -*- coding: utf-8 -*-
GRADE_12_DATA = {
    "warmup": [
        {"id": "g12-wu-6", "text": "Đồ thị hàm số phân thức bậc nhất y = (ax + b) / (cx + d) có đường tiệm cận đứng là đường thẳng nào?", "answer": "x = -d / c"},
        {"id": "g12-wu-7", "text": "Hằng số Planck h có giá trị xấp xỉ bằng bao nhiêu Jun giây (J.s)?", "answer": "6,626 x 10^-34 J.s"},
        {"id": "g12-wu-8", "text": "Phản ứng thủy phân chất béo trong môi trường kiềm còn được gọi là phản ứng gì?", "answer": "Phản ứng xà phòng hóa"},
        {"id": "g12-wu-9", "text": "Đoạn thơ mở đầu bằng câu 'Sông Mã xa rồi Tây Tiến ơi! / Nhớ về rừng núi, nhớ chơi vơi' là kiệt tác của nhà thơ nào?", "answer": "Quang Dũng"},
        {"id": "g12-wu-10", "text": "Trong thí nghiệm Young về giao thoa ánh sáng, công thức tính khoảng vân i theo bước sóng λ, khoảng cách hai khe a và khoảng cách đến màn D là gì?", "answer": "i = lambda . D / a"},
        {"id": "g12-wu-11", "text": "Trong không gian Oxyz, phương trình mặt cầu tâm I(a; b; c) bán kính R có dạng tổng quát là gì?", "answer": "(x - a)^2 + (y - b)^2 + (z - c)^2 = R^2"},
        {"id": "g12-wu-12", "text": "Kim loại nào có độ dẻo cao nhất và có thể dát mỏng đến mức ánh sáng có thể lọt qua?", "answer": "Vàng (Au)"},
        {"id": "g12-wu-13", "text": "Trật tự thế giới hai cực được xác lập sau Chiến tranh thế giới thứ hai mang tên hội nghị quốc tế nào?", "answer": "Hội nghị Ianta (Yalta)"},
        {"id": "g12-wu-14", "text": "Mã di truyền có tính thoái hóa nghĩa là gì?", "answer": "Nhiều bộ ba khác nhau cùng mã hóa cho một loại axit amin"},
        {"id": "g12-wu-15", "text": "Số phức z = a + bi có môđun được tính bằng công thức nào?", "answer": "căn bậc hai của (a^2 + b^2)"},
        {"id": "g12-wu-16", "text": "Hiện tượng ánh sáng giải phóng các electron liên kết trong chất bán dẫn tạo thành electron dẫn và lỗ trống gọi là hiện tượng gì?", "answer": "Quang điện trong"},
        {"id": "g12-wu-17", "text": "Cacbohiđrat nào là thành phần chính cấu tạo nên màng tế bào thực vật và có nhiều trong sợi bông, gỗ?", "answer": "Xenlulozơ (Cellulose)"},
        {"id": "g12-wu-18", "text": "Ai là tác giả của thiên tùy bút bất hủ 'Người lái đò Sông Đà'?", "answer": "Nguyễn Tuân"},
        {"id": "g12-wu-19", "text": "Đơn vị đo mức cường độ âm phổ biến trong vật lý là gì?", "answer": "Đề-xi-ben (Decibel, ký hiệu dB) hoặc Ben (B)"},
        {"id": "g12-wu-20", "text": "Nguyên hàm của hàm số f(x) = e^x là hàm số nào?", "answer": "e^x + C"},
        {"id": "g12-wu-21", "text": "Kim loại kiềm mềm nhất và có khối lượng riêng nhỏ nhất trong tất cả các kim loại là kim loại nào?", "answer": "Liti (Li)"},
        {"id": "g12-wu-22", "text": "Chiến dịch quân sự quyết định mở màn cho cuộc Tổng tiến công và nổi dậy mùa Xuân năm 1975 là chiến dịch nào?", "answer": "Chiến dịch Tây Nguyên"},
        {"id": "g12-wu-23", "text": "Cấu trúc Operon Lac ở vi khuẩn E. coli gồm những vùng nào theo thứ tự?", "answer": "Vùng khởi động (P), vùng vận hành (O) và các gen cấu trúc (Z, Y, A)"},
        {"id": "g12-wu-24", "text": "Vectơ pháp tuyến của mặt phẳng (P): 2x - 3y + z - 5 = 0 có tọa độ là gì?", "answer": "(2; -3; 1)"},
        {"id": "g12-wu-25", "text": "Trong mạch dao động LC lí tưởng, năng lượng điện từ được bảo toàn và chuyển hóa qua lại giữa năng lượng điện trường trong tụ điện và năng lượng gì trong cuộn cảm?", "answer": "Năng lượng từ trường"},
        {"id": "g12-wu-26", "text": "Chất nào sau đây là amino axit đơn giản nhất có công thức phân tử C2H5NO2?", "answer": "Glyxin (Glycine)"},
        {"id": "g12-wu-27", "text": "Tác phẩm văn học nào của nhà văn Kim Lân lấy bối cảnh nạn đói khủng khiếp năm Ất Dậu 1945?", "answer": "Vợ nhặt"},
        {"id": "g12-wu-28", "text": "Học thuyết tiến hóa tổng hợp hiện đại coi nhân tố tiến hóa nào là nhân tố duy nhất định hướng quá trình tiến hóa?", "answer": "Chọn lọc tự nhiên"},
        {"id": "g12-wu-29", "text": "Quần xã đỉnh cực là trạng thái ổn định cuối cùng của quá trình sinh thái nào?", "answer": "Diễn thế sinh thái"},
        {"id": "g12-wu-30", "text": "Đạo hàm của hàm số mũ y = a^x (a > 0, a khác 1) là gì?", "answer": "a^x . ln a"},
        {"id": "g12-wu-31", "text": "Bức xạ điện từ có bước sóng ngắn hơn ánh sáng nhìn thấy nhưng dài hơn tia X được gọi là gì?", "answer": "Tia tử ngoại (tia cực tím, UV)"},
        {"id": "g12-wu-32", "text": "Polime nào được dùng làm chảo chống dính nhờ tính bền nhiệt và chống ăn mòn cực tốt?", "answer": "Teflon (PTFE)"},
        {"id": "g12-wu-33", "text": "Tập thơ 'Việt Bắc' của nhà thơ Tố Hữu đã phản ánh trọn vẹn cuộc kháng chiến trường kỳ chống đế quốc nào?", "answer": "Thực dân Pháp"},
        {"id": "g12-wu-34", "text": "Đại lượng đặc trưng cho mức độ bền vững của hạt nhân nguyên tử là năng lượng liên kết gì?", "answer": "Năng lượng liên kết riêng"},
        {"id": "g12-wu-35", "text": "Tích phân từ 0 đến 1 của hàm số f(x) = 2x dx bằng bao nhiêu?", "answer": "1"},
        {"id": "g12-wu-36", "text": "Phương pháp nào dùng dòng điện để điều chế các kim loại hoạt động hóa học mạnh như Na, Mg, Al?", "answer": "Điện phân nóng chảy"},
        {"id": "g12-wu-37", "text": "Bản Hiến chương Liên Hợp Quốc có hiệu lực từ ngày tháng năm nào, trở thành Ngày Liên Hợp Quốc?", "answer": "24/10/1945"},
        {"id": "g12-wu-38", "text": "Quy luật di truyền liên kết gen hoàn toàn do nhà bác học nào phát hiện trên đối tượng ruồi giấm?", "answer": "Thomas Hunt Morgan"},
        {"id": "g12-wu-39", "text": "Vùng đồi núi chiếm bao nhiêu phần diện tích lãnh thổ đất liền nước ta?", "answer": "3/4 diện tích"},
        {"id": "g12-wu-40", "text": "Hiện tượng một chùm ánh sáng trắng đi qua lăng kính bị phân tách thành dải nhiều màu từ đỏ đến tím gọi là hiện tượng gì?", "answer": "Tán sắc ánh sáng"}
    ],
    "acceleration": [
        {"id": "g12-tt-6", "text": "Giá trị lớn nhất của hàm số y = -x^4 + 2x^2 + 3 trên đoạn [0; 2] bằng bao nhiêu?", "options": ["4", "3", "-5", "5"], "answer": "4", "timeLimitSeconds": 20},
        {"id": "g12-tt-7", "text": "Trong thí nghiệm Young về giao thoa ánh sáng đơn sắc, nếu tăng khoảng cách D giữa hai khe và màn lên gấp đôi thì khoảng vân i sẽ:", "options": ["Tăng lên gấp đôi", "Giảm đi một nửa", "Tăng lên 4 lần", "Không đổi"], "answer": "Tăng lên gấp đôi", "timeLimitSeconds": 20},
        {"id": "g12-tt-8", "text": "Chất nào sau đây tác dụng với dung dịch AgNO3 trong NH3 đun nóng tạo kết tủa bạc kim loại (phản ứng tráng gương)?", "options": ["Glucozơ", "Saccarozơ", "Tinh bột", "Xenlulozơ"], "answer": "Glucozơ", "timeLimitSeconds": 20},
        {"id": "g12-tt-9", "text": "Nhân vật người đàn bà hàng chài trong tác phẩm 'Chiếc thuyền ngoài xa' của Nguyễn Minh Châu thể hiện nét đẹp tâm hồn nào?", "options": ["Tình mẫu tử tha thiết và lòng bao dung, nhẫn nại", "Khát vọng tự do và độc lập", "Lòng căm thù giặc sâu sắc", "Tính cách ngang tàng, nổi loạn"], "answer": "Tình mẫu tử tha thiết và lòng bao dung, nhẫn nại", "timeLimitSeconds": 20},
        {"id": "g12-tt-10", "text": "Quá trình nào sau đây là nguyên nhân chính dẫn đến sự phân ly tính trạng độc lập trong giảm phân?", "options": ["Sự phân ly độc lập và tổ hợp tự do của các cặp nhiễm sắc thể tương đồng", "Trao đổi chéo giữa các crômatit", "Đột biến số lượng NST", "Sự co xoắn của NST"], "answer": "Sự phân ly độc lập và tổ hợp tự do của các cặp nhiễm sắc thể tương đồng", "timeLimitSeconds": 20},
        {"id": "g12-tt-11", "text": "Trong không gian Oxyz, phương trình mặt phẳng đi qua điểm M(1; 2; 3) và nhận vectơ n(2; -1; 1) làm vectơ pháp tuyến là:", "options": ["2x - y + z - 3 = 0", "2x - y + z + 3 = 0", "x + 2y + 3z - 3 = 0", "2x - y + z = 0"], "answer": "2x - y + z - 3 = 0", "timeLimitSeconds": 20},
        {"id": "g12-tt-12", "text": "Trong mạch điện xoay chiều RLC nối tiếp có hiện tượng cộng hưởng điện khi tần số góc ω thỏa mãn hệ thức nào?", "options": ["omega = 1 / can(L.C)", "omega = can(L.C)", "omega = L / C", "omega = R / can(L.C)"], "answer": "omega = 1 / can(L.C)", "timeLimitSeconds": 20},
        {"id": "g12-tt-13", "text": "Polime nào sau đây thuộc loại TƠ BÁN TỔNG HỢP (tơ nhân tạo)?", "options": ["Tơ visco (hoặc tơ axetat)", "Tơ nilon-6,6", "Tơ tằm", "Tơ olon (nitron)"], "answer": "Tơ visco (hoặc tơ axetat)", "timeLimitSeconds": 20},
        {"id": "g12-tt-14", "text": "Hai quốc gia nào giữ vị trí đứng đầu thế giới về diện tích rừng nhiệt đới xích đạo?", "options": ["Brazil và Indonesia", "Hoa Kỳ và Canada", "Nga và Trung Quốc", "Australia và Ấn Độ"], "answer": "Brazil và Indonesia", "timeLimitSeconds": 20},
        {"id": "g12-tt-15", "text": "Đoạn trích 'Đất Nước' thuộc phần đầu chương mấy của trường ca 'Mặt đường khát vọng' (Nguyễn Khoa Điềm)?", "options": ["Chương V", "Chương I", "Chương III", "Chương VII"], "answer": "Chương V", "timeLimitSeconds": 20},
        {"id": "g12-tt-16", "text": "Nghiệm của phương trình mũ: 2^(x - 1) = 8 là:", "options": ["x = 4", "x = 3", "x = 5", "x = 2"], "answer": "x = 4", "timeLimitSeconds": 20},
        {"id": "g12-tt-17", "text": "Kim loại nào sau đây có tính khử MẠNH NHẤT trong dãy điện hóa?", "options": ["Kali (K)", "Sắt (Fe)", "Đồng (Cu)", "Bạc (Ag)"], "answer": "Kali (K)", "timeLimitSeconds": 20},
        {"id": "g12-tt-18", "text": "Tia X (tia Rơn-ghen) KHÔNG CÓ ứng dụng nào sau đây?", "options": ["Sấy khô nông sản thực phẩm", "Chụp X-quang y tế chẩn đoán gãy xương", "Kiểm tra khuyết tật bên trong vật đúc", "Kiểm tra hành lý sân bay"], "answer": "Sấy khô nông sản thực phẩm", "timeLimitSeconds": 20},
        {"id": "g12-tt-19", "text": "Quần thể tự phối (tự thụ phấn hoặc giao phối cận huyết) qua nhiều thế hệ có xu hướng biến đổi cấu trúc di truyền như thế nào?", "options": ["Tăng dần tần số kiểu gen đồng hợp, giảm dần dị hợp", "Tăng dần dị hợp, giảm dần đồng hợp", "Tần số alen bị biến đổi hoàn toàn", "Đa dạng di truyền tăng lên"], "answer": "Tăng dần tần số kiểu gen đồng hợp, giảm dần dị hợp", "timeLimitSeconds": 20},
        {"id": "g12-tt-20", "text": "Hiệp hội các quốc gia Đông Nam Á (ASEAN) chính thức kết nạp Việt Nam làm thành viên thứ 7 vào năm nào?", "options": ["1995", "1997", "1999", "1991"], "answer": "1995", "timeLimitSeconds": 20},
        {"id": "g12-tt-21", "text": "Cho hình phẳng giới hạn bởi đồ thị y = x^2, trục hoành Ox và hai đường thẳng x = 0, x = 3 quay quanh Ox. Thể tích khối tròn xoay tạo thành là:", "options": ["243.pi / 5", "81.pi / 5", "27.pi", "9.pi"], "answer": "243.pi / 5", "timeLimitSeconds": 20},
        {"id": "g12-tt-22", "text": "Kim loại kiềm thổ nào khi phản ứng với nước ở nhiệt độ thường tạo dung dịch vôi trong làm đục khí CO2?", "options": ["Canxi (Ca)", "Bari (Ba)", "Magie (Mg)", "Beri (Be)"], "answer": "Canxi (Ca)", "timeLimitSeconds": 20},
        {"id": "g12-tt-23", "text": "Một sóng cơ hình sin có tần số f = 50 Hz lan truyền với bước sóng λ = 0,4 m. Tốc độ truyền sóng là:", "options": ["20 m/s", "125 m/s", "200 m/s", "12,5 m/s"], "answer": "20 m/s", "timeLimitSeconds": 20},
        {"id": "g12-tt-24", "text": "Hình tượng 'tiếng đàn Lorca' trong bài thơ 'Đàn ghi ta của Lorca' (Thanh Thảo) biểu tượng cho điều gì?", "options": ["Nghệ thuật bất tử và khát vọng tự do", "Nỗi buồn chia ly", "Cuộc đời phiêu bạt giang hồ", "Sức mạnh chiến tranh"], "answer": "Nghệ thuật bất tử và khát vọng tự do", "timeLimitSeconds": 20},
        {"id": "g12-tt-25", "text": "Vùng kinh tế trọng điểm phía Nam bao gồm địa bàn của bao nhiêu tỉnh, thành phố?", "options": ["8 tỉnh thành", "6 tỉnh thành", "10 tỉnh thành", "5 tỉnh thành"], "answer": "8 tỉnh thành", "timeLimitSeconds": 20},
        {"id": "g12-tt-26", "text": "Môđun của số phức z = 3 - 4i bằng bao nhiêu?", "options": ["5", "7", "25", "1"], "answer": "5", "timeLimitSeconds": 20},
        {"id": "g12-tt-27", "text": "Hợp chất sắt nào sau đây vừa có tính oxi hóa vừa có tính khử?", "options": ["FeO (Sắt II oxit)", "Fe2O3", "Fe2(SO4)3", "Fe(OH)3"], "answer": "FeO (Sắt II oxit)", "timeLimitSeconds": 20},
        {"id": "g12-tt-28", "text": "Đặc trưng sinh lý của âm bao gồm:", "options": ["Độ cao, độ to và âm sắc", "Tần số, cường độ âm và đồ thị âm", "Tốc độ truyền âm và bước sóng", "Biên độ và tần số"], "answer": "Độ cao, độ to và âm sắc", "timeLimitSeconds": 20},
        {"id": "g12-tt-29", "text": "Bệnh máu khó đông ở người do alen lặn nằm trên nhiễm sắc thể nào quy định?", "options": ["Nhiễm sắc thể giới tính X (không có alen trên Y)", "Nhiễm sắc thể giới tính Y", "Nhiễm sắc thể thường số 21", "Nhiễm sắc thể thường số 9"], "answer": "Nhiễm sắc thể giới tính X (không có alen trên Y)", "timeLimitSeconds": 20},
        {"id": "g12-tt-30", "text": "Thắng lợi ngoại giao nào của Việt Nam năm 1973 đã buộc quân đội Mỹ và đồng minh phải rút khỏi miền Nam?", "options": ["Hiệp định Paris", "Hiệp định Geneva", "Hiệp ước Sơ bộ", "Tuyên bố chung Washington"], "answer": "Hiệp định Paris", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g12-vd-10-4", "points": 10, "text": "Cho hàm số y = f(x) có đạo hàm f'(x) = (x - 1)(x + 2). Hỏi hàm số đã cho có bao nhiêu điểm cực trị?", "answer": "2 điểm cực trị"},
        {"id": "g12-vd-10-5", "points": 10, "text": "Hợp chất hữu cơ nào có công thức phân tử C6H12O6 là đường ngọt chủ yếu trong quả nho chín?", "answer": "Glucozơ"},
        {"id": "g12-vd-10-6", "points": 10, "text": "Tia phóng xạ nào mang điện tích dương bản chất là dòng hạt nhân nguyên tử Heli (He 4/2)?", "answer": "Tia alpha (α)"},
        {"id": "g12-vd-10-7", "points": 10, "text": "Hình tượng 'cây xà nu' biểu tượng cho sức sống kiên cường, bất khuất của đồng bào Tây Nguyên trong truyện ngắn nào của Nguyễn Trung Thành?", "answer": "Rừng xà nu"},
        {"id": "g12-vd-10-8", "points": 10, "text": "Theo định luật Hardy - Weinberg, một quần thể cân bằng di truyền có tần số alen A là p và a là q. Tỉ lệ kiểu gen dị hợp Aa là bao nhiêu?", "answer": "2pq"},
        {"id": "g12-vd-10-9", "points": 10, "text": "Vịnh biển kín nào ở Duyên hải Nam Trung Bộ được đánh giá là nơi có điều kiện xây dựng cảng nước sâu tốt nhất nước ta?", "answer": "Vịnh Cam Ranh (hoặc Vịnh Vân Phong)"},
        {"id": "g12-vd-10-10", "points": 10, "text": "Đại hội Đảng toàn quốc lần thứ mấy (năm 1991) đã thông qua Cương lĩnh xây dựng đất nước trong thời kỳ quá độ lên chủ nghĩa xã hội?", "answer": "Đại hội VII (Đại hội 7)"},
        {"id": "g12-vd-20-4", "points": 20, "text": "Tính tích phân I = nguyên hàm từ 0 đến pi/2 của hàm số sin x dx?", "answer": "I = 1"},
        {"id": "g12-vd-20-5", "points": 20, "text": "Chất rắn màu trắng khó tan trong nước và có tính chất lưỡng tính (tan được trong cả axit mạnh và kiềm mạnh) của nhôm có công thức hóa học là gì?", "answer": "Al(OH)3 hoặc Al2O3"},
        {"id": "g12-vd-20-6", "points": 20, "text": "Một chất phóng xạ có chu kỳ bán rã T = 8 ngày đêm. Sau 24 ngày đêm, lượng chất phóng xạ còn lại bằng bao nhiêu phần trăm lượng ban đầu?", "answer": "12,5% (1/8)"},
        {"id": "g12-vd-20-7", "points": 20, "text": "Vở kịch 'Hồn Trương Ba, da hàng thịt' của Lưu Quang Vũ gửi gắm triết lý sống gì về sự thống nhất giữa tâm hồn và thể xác?", "answer": "Con người phải được sống là chính mình, thống nhất hài hòa giữa linh hồn thanh cao và thể xác"},
        {"id": "g12-vd-20-8", "points": 20, "text": "Đột biến gen xảy ra ở một cặp nucleotit làm chuỗi polipeptit do gen mã hóa không thay đổi axit amin nào được gọi là dạng đột biến gì?", "answer": "Đột biến đồng nghĩa (đột biến câm)"},
        {"id": "g12-vd-20-9", "points": 20, "text": "Mỏ dầu thô đầu tiên được phát hiện và khai thác công nghiệp ở thềm lục địa phía Nam nước ta có tên là gì?", "answer": "Mỏ Bạch Hổ"},
        {"id": "g12-vd-20-10", "points": 20, "text": "Tổng thống đầu tiên của nước Cộng hòa Nam Phi được bầu cử dân chủ năm 1994, chấm dứt chế độ phân biệt chủng tộc Apartheid là ai?", "answer": "Nelson Mandela"},
        {"id": "g12-vd-30-4", "points": 30, "text": "Trong không gian Oxyz, tìm khoảng cách từ gốc tọa độ O đến mặt phẳng (P): 2x - 2y + z - 9 = 0?", "answer": "3"},
        {"id": "g12-vd-30-5", "points": 30, "text": "Điện phân hoàn toàn dung dịch chứa 16 gam CuSO4 với điện cực trơ đến khi catot xuất hiện bọt khí thì dừng lại. Tính khối lượng kim loại đồng thu được ở catot (biết Cu=64, S=32, O=16)?", "answer": "6,4 gam"},
        {"id": "g12-vd-30-6", "points": 30, "text": "Công thoát electron của kim loại kẽm là A = 3,55 eV (1 eV = 1,6 x 10^-19 J). Tính giới hạn quang điện λ0 của kẽm theo đơn vị micromet?", "answer": "0,35 micromet (xấp xỉ 0,35 μm)"},
        {"id": "g12-vd-30-7", "points": 30, "text": "Đoạn trích 'Vợ chồng A Phủ' của Tô Hoài miêu tả sức sống tiềm tàng trỗi dậy mãnh liệt của nhân vật Mị trong đêm tình mùa xuân khi nghe tiếng gọi của nhạc cụ nào?", "answer": "Tiếng sáo gọi bạn tình"},
        {"id": "g12-vd-30-8", "points": 30, "text": "Trong một quần thể thực vật giao phấn ngẫu nhiên, alen A quy định hoa đỏ trội hoàn toàn so với alen a quy định hoa trắng. Biết quần thể có 16% cây hoa trắng. Tính tần số của alen A?", "answer": "0,6 (60%)"},
        {"id": "g12-vd-30-9", "points": 30, "text": "Đường biên giới quốc gia trên biển của nước ta là ranh giới ngoài của vùng biển nào theo luật biển quốc tế?", "answer": "Lãnh hải (cách đường cơ sở 12 hải lý)"},
        {"id": "g12-vd-30-10", "points": 30, "text": "Đại hội nào của Đảng Cộng sản Việt Nam đã chính thức khẳng định 'Kinh tế tư nhân là một động lực quan trọng của nền kinh tế thị trường định hướng XHCN'?", "answer": "Đại hội XII (năm 2016) hoặc Nghị quyết Hội nghị TW 5 khóa XII"}
    ]
}
