# -*- coding: utf-8 -*-
GRADE_5_DATA = {
    "warmup": [
        {"id": "g5-wu-6", "text": "Công thức tính vận tốc (v) khi biết quãng đường (s) và thời gian (t) là gì?", "answer": "v = s / t (hoặc v = s : t)"},
        {"id": "g5-wu-7", "text": "Viết phân số 3/4 dưới dạng số thập phân là bao nhiêu?", "answer": "0,75"},
        {"id": "g5-wu-8", "text": "Chủ tịch Hồ Chí Minh đọc bản 'Tuyên ngôn Độc lập' khai sinh ra nước Việt Nam Dân chủ Cộng hòa vào ngày tháng năm nào?", "answer": "2/9/1945"},
        {"id": "g5-wu-9", "text": "Châu lục nào có diện tích và dân số lớn nhất thế giới?", "answer": "Châu Á"},
        {"id": "g5-wu-10", "text": "Các từ 'đậu' trong 'hạt đậu' và 'chim đậu trên cành' có quan hệ với nhau như thế nào về mặt ngữ nghĩa?", "answer": "Từ đồng âm"},
        {"id": "g5-wu-11", "text": "Muốn tính diện tích hình tam giác, ta lấy độ dài đáy nhân với chiều cao (cùng đơn vị đo) rồi chia cho mấy?", "answer": "Chia cho 2"},
        {"id": "g5-wu-12", "text": "Năng lượng từ nguồn tự nhiên nào giúp cây xanh quang hợp và tạo ra vòng tuần hoàn của nước?", "answer": "Năng lượng Mặt Trời"},
        {"id": "g5-wu-13", "text": "Chiến dịch Điện Biên Phủ 'lừng lẫy năm châu, chấn động địa cầu' toàn thắng vào năm nào?", "answer": "1954"},
        {"id": "g5-wu-14", "text": "Hình hộp chữ nhật có tất cả bao nhiêu mặt?", "answer": "6 mặt"},
        {"id": "g5-wu-15", "text": "Nước ta có đường bờ biển dài khoảng bao nhiêu ki-lô-mét?", "answer": "Khoảng 3260 km"},
        {"id": "g5-wu-16", "text": "Số 0,08 được viết dưới dạng tỉ số phần trăm là bao nhiêu?", "answer": "8%"},
        {"id": "g5-wu-17", "text": "Trong câu ghép, các vế câu thường được nối với nhau bằng cặp từ loại nào (ví dụ: vì... nên...)?", "answer": "Cặp quan hệ từ"},
        {"id": "g5-wu-18", "text": "Bác Hồ ra đi tìm đường cứu nước từ bến cảng nào vào ngày 5/6/1911?", "answer": "Bến cảng Nhà Rồng"},
        {"id": "g5-wu-19", "text": "Châu lục nào được bao phủ quanh năm bởi lớp băng tuyết dày và lạnh giá nhất Trái Đất?", "answer": "Châu Nam Cực"},
        {"id": "g5-wu-20", "text": "Hiện tượng que đóm cháy thành than tro là biến đổi vật lý hay biến đổi hóa học?", "answer": "Biến đổi hóa học"},
        {"id": "g5-wu-21", "text": "1 mét khối (m3) bằng bao nhiêu lít nước?", "answer": "1000 lít (hoặc 1000 dm3)"},
        {"id": "g5-wu-22", "text": "Đảng Cộng sản Việt Nam được thành lập vào ngày tháng năm nào tại Hương Cảng (Trung Quốc)?", "answer": "3/2/1930"},
        {"id": "g5-wu-23", "text": "Đỉnh Everest (Chomolungma) thuộc dãy núi nào ở châu Á?", "answer": "Dãy Himalaya"},
        {"id": "g5-wu-24", "text": "Từ nào sau đây là từ nhiều nghĩa: 'chân' trong 'chân bàn' hay 'chân người'?", "answer": "Từ nhiều nghĩa"},
        {"id": "g5-wu-25", "text": "Cơ quan sinh sản của thực vật có hoa là bộ phận nào?", "answer": "Hoa"},
        {"id": "g5-wu-26", "text": "Chu vi của một hình tròn có bán kính r được tính bằng công thức nào?", "answer": "C = r x 2 x 3,14 (hoặc d x 3,14)"},
        {"id": "g5-wu-27", "text": "Hai quần đảo lớn Hoàng Sa và Trường Sa thuộc chủ quyền thiêng liêng của quốc gia nào?", "answer": "Việt Nam"},
        {"id": "g5-wu-28", "text": "Đại thắng mùa Xuân 1975 giải phóng hoàn toàn miền Nam, thống nhất đất nước kết thúc vào ngày nào?", "answer": "30 tháng 4 năm 1975"},
        {"id": "g5-wu-29", "text": "Kim loại nào dẫn điện tốt nhất và thường được dùng làm ruột dây dẫn điện phổ biến hiện nay?", "answer": "Đồng (hoặc nhôm)"},
        {"id": "g5-wu-30", "text": "Diện tích hình thang bằng tổng độ dài hai đáy nhân với chiều cao rồi chia cho mấy?", "answer": "Chia cho 2"},
        {"id": "g5-wu-31", "text": "Kim tự tháp Kê-ốp nổi tiếng thế giới nằm ở quốc gia nào thuộc châu Phi?", "answer": "Ai Cập"},
        {"id": "g5-wu-32", "text": "Đại từ dùng để xưng hô ngôi thứ nhất số ít thường gặp là từ nào?", "answer": "Tôi (hoặc tớ, mình, em)"},
        {"id": "g5-wu-33", "text": "Nhà máy thủy điện lớn đầu tiên được xây dựng trên sông Đà ở miền Bắc nước ta là nhà máy nào?", "answer": "Thủy điện Hòa Bình"},
        {"id": "g5-wu-34", "text": "Loài ếch sinh sản bằng cách đẻ trứng hay đẻ con?", "answer": "Đẻ trứng"},
        {"id": "g5-wu-35", "text": "Một người đi xe máy với vận tốc 40 km/h trong 2 giờ. Quãng đường người đó đi được là bao nhiêu?", "answer": "80 km"},
        {"id": "g5-wu-36", "text": "Dòng sông nào dài nhất thế giới chảy qua khu vực châu Phi?", "answer": "Sông Nin (Nile)"},
        {"id": "g5-wu-37", "text": "Bài thơ 'Hạt gạo làng ta' do nhà thơ nào sáng tác khi còn ở lứa tuổi thiếu nhi?", "answer": "Trần Đăng Khoa"},
        {"id": "g5-wu-38", "text": "Phong trào Đông Du đầu thế kỷ XX gắn liền với nhà yêu nước lỗi lạc nào?", "answer": "Phan Bội Châu"},
        {"id": "g5-wu-39", "text": "Đơn vị đo thể tích dm3 còn có tên gọi thông dụng đời sống là gì?", "answer": "Lít (l)"},
        {"id": "g5-wu-40", "text": "Hiện tượng nóng lên toàn cầu do hiệu ứng nhà kính chủ yếu xuất phát từ sự gia tăng của chất khí nào?", "answer": "Khí cacbonic (CO2)"}
    ],
    "acceleration": [
        {"id": "g5-tt-6", "text": "Biết 25% của một số là 50. Số đó là bao nhiêu?", "options": ["100", "150", "200", "250"], "answer": "200", "timeLimitSeconds": 20},
        {"id": "g5-tt-7", "text": "Chiến dịch lịch sử nào đã kết thúc thắng lợi cuộc kháng chiến chống Mỹ cứu nước năm 1975?", "options": ["Chiến dịch Tây Nguyên", "Chiến dịch Huế - Đà Nẵng", "Chiến dịch Hồ Chí Minh", "Chiến dịch Điện Biên Phủ trên không"], "answer": "Chiến dịch Hồ Chí Minh", "timeLimitSeconds": 20},
        {"id": "g5-tt-8", "text": "Rừng rậm nhiệt đới lớn nhất thế giới nằm ở lưu vực con sông nào tại Nam Mỹ?", "options": ["Sông Amazon", "Sông Mississippi", "Sông Nile", "Sông Danube"], "answer": "Sông Amazon", "timeLimitSeconds": 20},
        {"id": "g5-tt-9", "text": "Cặp quan hệ từ nào sau đây biểu thị mối quan hệ 'Nguyên nhân - Kết quả'?", "options": ["Mặc dù... nhưng...", "Nếu... thì...", "Vì... nên...", "Càng... càng..."], "answer": "Vì... nên...", "timeLimitSeconds": 20},
        {"id": "g5-tt-10", "text": "Một hình lập phương có cạnh bằng 3cm. Thể tích của hình lập phương đó là bao nhiêu?", "options": ["9 cm3", "18 cm3", "27 cm3", "36 cm3"], "answer": "27 cm3", "timeLimitSeconds": 20},
        {"id": "g5-tt-11", "text": "Ai là Tổng Tư lệnh tối cao của Quân đội nhân dân Việt Nam trong chiến dịch Điện Biên Phủ 1954?", "options": ["Đại tướng Võ Nguyên Giáp", "Đại tướng Văn Tiến Dũng", "Đại tướng Nguyễn Chí Thanh", "Trung tướng Hoàng Văn Thái"], "answer": "Đại tướng Võ Nguyên Giáp", "timeLimitSeconds": 20},
        {"id": "g5-tt-12", "text": "Nguồn năng lượng nào sau đây là NĂNG LƯỢNG TÁI TẠO (năng lượng sạch)?", "options": ["Than đá", "Dầu mỏ", "Khí đốt tự nhiên", "Năng lượng gió"], "answer": "Năng lượng gió", "timeLimitSeconds": 20},
        {"id": "g5-tt-13", "text": "Một ca nô xuôi dòng với vận tốc 24 km/h. Vận tốc dòng nước là 2 km/h. Vận tốc thực của ca nô khi nước lặng là bao nhiêu?", "options": ["26 km/h", "22 km/h", "20 km/h", "28 km/h"], "answer": "22 km/h", "timeLimitSeconds": 20},
        {"id": "g5-tt-14", "text": "Châu Đại Dương bao gồm lục địa Australia và các đảo ở đại dương nào?", "options": ["Thái Bình Dương", "Ấn Độ Dương", "Đại Tây Dương", "Bắc Băng Dương"], "answer": "Thái Bình Dương", "timeLimitSeconds": 20},
        {"id": "g5-tt-15", "text": "Dãy số nào sau đây được xếp theo thứ tự TĂNG DẦN?", "options": ["0,35; 0,53; 0,5; 0,05", "0,05; 0,35; 0,5; 0,53", "0,53; 0,5; 0,35; 0,05", "0,05; 0,5; 0,35; 0,53"], "answer": "0,05; 0,35; 0,5; 0,53", "timeLimitSeconds": 20},
        {"id": "g5-tt-16", "text": "Tác phẩm văn học nổi tiếng 'Dế Mèn phiêu lưu ký' là của nhà văn nào?", "options": ["Tô Hoài", "Đoàn Giỏi", "Nguyễn Nhật Ánh", "Phạm Hổ"], "answer": "Tô Hoài", "timeLimitSeconds": 20},
        {"id": "g5-tt-17", "text": "Hợp tử phát triển thành gì trong quá trình sinh sản hữu tính của thực vật?", "options": ["Hạt phấn", "Noãn", "Phôi", "Bao phấn"], "answer": "Phôi", "timeLimitSeconds": 20},
        {"id": "g5-tt-18", "text": "Một hình tròn có đường kính d = 10cm. Diện tích của hình tròn đó là bao nhiêu?", "options": ["31,4 cm2", "78,5 cm2", "314 cm2", "15,7 cm2"], "answer": "78,5 cm2", "timeLimitSeconds": 20},
        {"id": "g5-tt-19", "text": "Đất nước nào sau đây ở Đông Nam Á KHÔNG GIÁP BIỂN?", "options": ["Lào", "Campuchia", "Thái Lan", "Myanmar"], "answer": "Lào", "timeLimitSeconds": 20},
        {"id": "g5-tt-20", "text": "Anh hùng nào đã lấy thân mình chèn lưng pháo trong chiến dịch Điện Biên Phủ 1954?", "options": ["Tô Vĩnh Diện", "Bế Văn Đàn", "Phan Đình Giót", "Cù Chính Lan"], "answer": "Tô Vĩnh Diện", "timeLimitSeconds": 20},
        {"id": "g5-tt-21", "text": "Phép tính: 4,8 x 0,25 tương đương với phép chia nào sau đây?", "options": ["4,8 : 2", "4,8 : 4", "4,8 : 5", "4,8 : 10"], "answer": "4,8 : 4", "timeLimitSeconds": 20},
        {"id": "g5-tt-22", "text": "Bệnh sốt rét lây truyền sang người qua trung gian là loài sinh vật nào?", "options": ["Ruồi nhà", "Muỗi Anophen", "Muỗi vằn", "Bọ chét"], "answer": "Muỗi Anophen", "timeLimitSeconds": 20},
        {"id": "g5-tt-23", "text": "Dòng sông nào được mệnh danh là 'Mẹ của các dòng sông' chảy qua 6 quốc gia châu Á?", "options": ["Sông Mê Kông", "Sông Hồng", "Sông Dương Tử", "Sông Hoàng Hà"], "answer": "Sông Mê Kông", "timeLimitSeconds": 20},
        {"id": "g5-tt-24", "text": "Trong câu 'Tuy nhà nghèo nhưng bạn Nam học rất giỏi', từ 'Tuy... nhưng...' biểu thị quan hệ gì?", "options": ["Nguyên nhân - kết quả", "Tương phản", "Tăng tiến", "Giả thiết - kết quả"], "answer": "Tương phản", "timeLimitSeconds": 20},
        {"id": "g5-tt-25", "text": "Một người đi xe đạp từ A đến B với vận tốc 12 km/h hết 1 giờ 30 phút. Quãng đường AB dài bao nhiêu km?", "options": ["15 km", "16 km", "18 km", "20 km"], "answer": "18 km", "timeLimitSeconds": 20},
        {"id": "g5-tt-26", "text": "Nơi diễn ra phong trào Xô viết Nghệ Tĩnh (1930 - 1931) thuộc hai tỉnh nào ngày nay?", "options": ["Nghệ An và Hà Tĩnh", "Thanh Hóa và Nghệ An", "Hà Tĩnh và Quảng Bình", "Nghệ An và Quảng Trị"], "answer": "Nghệ An và Hà Tĩnh", "timeLimitSeconds": 20},
        {"id": "g5-tt-27", "text": "Loài động vật nào sau đây là ĐỘNG VẬT ĐẺ CON?", "options": ["Cá voi", "Đà điểu", "Cá chép", "Chim bồ câu"], "answer": "Cá voi", "timeLimitSeconds": 20},
        {"id": "g5-tt-28", "text": "Kênh đào nào nối liền Địa Trung Hải và Biển Đỏ, rút ngắn đường hàng hải từ châu Âu sang châu Á?", "options": ["Kênh đào Panama", "Kênh đào Suez", "Kênh đào Kiel", "Kênh đào Corinth"], "answer": "Kênh đào Suez", "timeLimitSeconds": 20},
        {"id": "g5-tt-29", "text": "Hình thang có độ dài hai đáy lần lượt là 14cm và 6cm, chiều cao là 5cm. Diện tích hình thang đó là bao nhiêu?", "options": ["50 cm2", "100 cm2", "60 cm2", "40 cm2"], "answer": "50 cm2", "timeLimitSeconds": 20},
        {"id": "g5-tt-30", "text": "Chất lỏng nào sau đây DẪN ĐIỆN tốt nhất?", "options": ["Nước cất tinh khiết", "Nước muối", "Cồn nguyên chất", "Dầu hỏa"], "answer": "Nước muối", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g5-vd-10-4", "points": 10, "text": "Tìm x biết: x x 100 = 345,6?", "answer": "3,456"},
        {"id": "g5-vd-10-5", "points": 10, "text": "Bản Hiệp định nào được ký kết năm 1973 buộc quân Mỹ phải rút toàn bộ quân đội về nước?", "answer": "Hiệp định Paris"},
        {"id": "g5-vd-10-6", "points": 10, "text": "Châu Âu nằm hoàn toàn ở bán cầu nào của Trái Đất theo đường xích đạo?", "answer": "Bán cầu Bắc"},
        {"id": "g5-vd-10-7", "points": 10, "text": "Công thức tính thể tích hình lập phương có cạnh a là gì?", "answer": "V = a x a x a (hoặc a^3)"},
        {"id": "g5-vd-10-8", "points": 10, "text": "Từ 'thiên' trong 'thiên nhiên' và 'thiên vị' có phải là từ đồng âm không?", "answer": "Phải (từ đồng âm)"},
        {"id": "g5-vd-10-9", "points": 10, "text": "Bệnh sốt xuất huyết do loại muỗi nào mang virus Dengue truyền bệnh?", "answer": "Muỗi vằn"},
        {"id": "g5-vd-10-10", "points": 10, "text": "Quốc gia nào có diện tích lãnh thổ lớn nhất thế giới, trải dài trên cả hai châu lục Á và Âu?", "answer": "Nga (Liên bang Nga)"},
        {"id": "g5-vd-20-4", "points": 20, "text": "Một ô tô đi quãng đường dài 120km hết 2 giờ 30 phút. Tính vận tốc của ô tô với đơn vị km/h?", "answer": "48 km/h"},
        {"id": "g5-vd-20-5", "points": 20, "text": "Đoàn tàu quân sự nào của không quân Mỹ đã bị quân dân miền Bắc bắn rơi trong trận 'Điện Biên Phủ trên không' tháng 12/1972?", "answer": "Máy bay B-52 (Pháo đài bay B-52)"},
        {"id": "g5-vd-20-6", "points": 20, "text": "Đại dương nào có độ sâu trung bình lớn nhất thế giới?", "answer": "Thái Bình Dương (sâu nhất tại rãnh Mariana)"},
        {"id": "g5-vd-20-7", "points": 20, "text": "Lãi suất tiết kiệm là 0,5% một tháng. Một người gửi tiết kiệm 10 000 000 đồng thì sau một tháng nhận được bao nhiêu tiền lãi?", "answer": "50 000 đồng"},
        {"id": "g5-vd-20-8", "points": 20, "text": "Bài thơ 'Việt Bắc' nổi tiếng mở đầu bằng câu 'Mình về mình có nhớ ta' do nhà thơ nào sáng tác?", "answer": "Tố Hữu"},
        {"id": "g5-vd-20-9", "points": 20, "text": "Quá trình chuyển đổi từ trứng thành ấu trùng, nhộng rồi bướm trưởng thành được gọi là quá trình biến thái gì?", "answer": "Biến thái hoàn toàn"},
        {"id": "g5-vd-20-10", "points": 20, "text": "Đường mòn Trường Sơn huyền thoại chi viện sức người, sức của cho chiến trường miền Nam còn mang tên vị lãnh tụ nào?", "answer": "Đường Hồ Chí Minh"},
        {"id": "g5-vd-30-4", "points": 30, "text": "Một bể bơi hình hộp chữ nhật có chiều dài 20m, chiều rộng 10m và chiều sâu 1,5m. Người ta bơm nước vào bể đạt 80% thể tích bể. Hỏi trong bể có bao nhiêu lít nước?", "answer": "240 000 lít"},
        {"id": "g5-vd-30-5", "points": 30, "text": "Ngày 30/4/1975, chiếc xe tăng mang số hiệu bao nhiêu của quân Giải phóng đã húc đổ cổng chính Dinh Độc Lập?", "answer": "Xe tăng 390"},
        {"id": "g5-vd-30-6", "points": 30, "text": "Tìm hai số có tổng bằng 104, biết rằng 1/2 số thứ nhất bằng 1/6 số thứ hai?", "answer": "Số thứ nhất là 26, số thứ hai là 78"},
        {"id": "g5-vd-30-7", "points": 30, "text": "Cây cầu đường sắt đầu tiên bắc qua sông Hồng tại Hà Nội mang tên cầu Long Biên được xây dựng vào thời kỳ thực dân Pháp đô hộ, ban đầu có tên là gì?", "answer": "Cầu Doumer (Đu-me)"},
        {"id": "g5-vd-30-8", "points": 30, "text": "Vận tốc ánh sáng truyền trong môi trường chân không xấp xỉ bằng bao nhiêu km trên giây?", "answer": "300 000 km/s (3 x 10^8 m/s)"},
        {"id": "g5-vd-30-9", "points": 30, "text": "Hai thành phố lớn nào của Nhật Bản đã từng bị ném bom nguyên tử vào tháng 8 năm 1945 trong Chiến tranh thế giới thứ hai?", "answer": "Hiroshima và Nagasaki"},
        {"id": "g5-vd-30-10", "points": 30, "text": "Lúc 7 giờ sáng, một xe máy đi từ A đến B với vận tốc 36 km/h. Cùng lúc đó, một ô tô đi từ B về A với vận tốc 54 km/h. Biết quãng đường AB dài 180 km. Hỏi hai xe gặp nhau lúc mấy giờ?", "answer": "9 giờ sáng"}
    ]
}
