# -*- coding: utf-8 -*-
GRADE_7_DATA = {
    "warmup": [
        {"id": "g7-wu-6", "text": "Hạt mang điện tích âm quay xung quanh hạt nhân nguyên tử là hạt gì?", "answer": "Electron (e)"},
        {"id": "g7-wu-7", "text": "Số hữu tỉ là số có thể viết được dưới dạng phân số a/b với a, b thuộc tập hợp số nào và b khác 0?", "answer": "Tập hợp số nguyên (Z)"},
        {"id": "g7-wu-8", "text": "Theo định lý phản xạ ánh sáng, góc phản xạ có độ lớn như thế nào so với góc tới?", "answer": "Bằng góc tới (i = i')"},
        {"id": "g7-wu-9", "text": "Tác phẩm lịch sử quân sự nổi tiếng 'Binh thư yếu lược' do danh tướng nào thời Trần biên soạn?", "answer": "Trần Quốc Tuấn (Trần Hưng Đạo)"},
        {"id": "g7-wu-10", "text": "Cơ quan nào ở thực vật chịu trách nhiệm chủ yếu cho quá trình quang hợp?", "answer": "Lá cây"},
        {"id": "g7-wu-11", "text": "Định lý hình học nào khẳng định trong tam giác vuông, bình phương cạnh huyền bằng tổng bình phương hai cạnh góc vuông?", "answer": "Định lý Pythagore (Pi-ta-go)"},
        {"id": "g7-wu-12", "text": "Biện pháp tu từ nào phóng đại quy mô, tính chất của sự vật, hiện tượng để gây ấn tượng mạnh mẽ?", "answer": "Nói quá (cường điệu)"},
        {"id": "g7-wu-13", "text": "Đơn vị đo tần số dao động của âm thanh trong hệ SI là gì?", "answer": "Héc (Hertz, ký hiệu Hz)"},
        {"id": "g7-wu-14", "text": "Nhà hàng hải người Bồ Đào Nha nào đã chỉ huy đoàn thám hiểm đầu tiên đi vòng quanh Trái Đất?", "answer": "Ferdinand Magellan"},
        {"id": "g7-wu-15", "text": "Khí khổng ở lá cây mở ra và đóng lại chủ yếu để điều tiết quá trình nào?", "answer": "Thoát hơi nước và trao đổi khí"},
        {"id": "g7-wu-16", "text": "Căn bậc hai số học của số 81 là số nào?", "answer": "9"},
        {"id": "g7-wu-17", "text": "Kim loại duy nhất ở thể lỏng ở nhiệt độ phòng bình thường là kim loại nào?", "answer": "Thủy ngân (Hg)"},
        {"id": "g7-wu-18", "text": "Ba lần kháng chiến chống quân xâm lược Mông - Nguyên diễn ra thắng lợi dưới triều đại nào?", "answer": "Nhà Trần"},
        {"id": "g7-wu-19", "text": "Điểm giao nhau của ba đường trung tuyến trong một tam giác được gọi là gì?", "answer": "Trọng tâm của tam giác"},
        {"id": "g7-wu-20", "text": "Biện pháp tu từ nào dùng cách diễn đạt tế nhị, uyển chuyển để tránh gây cảm giác đau buồn, nặng nề?", "answer": "Nói giảm nói tránh"},
        {"id": "g7-wu-21", "text": "Âm thanh có tần số nhỏ hơn 20 Hz mà tai người bình thường không nghe được gọi là gì?", "answer": "Hạ âm"},
        {"id": "g7-wu-22", "text": "Tác phẩm hội họa nổi tiếng 'Nàng Mona Lisa' (La Gioconda) là kiệt tác của danh họa thời Phục hưng nào?", "answer": "Leonardo da Vinci"},
        {"id": "g7-wu-23", "text": "Phân tử nước (H2O) gồm có 2 nguyên tử hiđro và 1 nguyên tử gì liên kết với nhau?", "answer": "Oxi (Oxygen)"},
        {"id": "g7-wu-24", "text": "Trong một tam giác cân, hai góc ở đáy có mối quan hệ như thế nào với nhau?", "answer": "Bằng nhau"},
        {"id": "g7-wu-25", "text": "Hệ tuần hoàn kín ở động vật gồm tim, động mạch, tĩnh mạch và hệ thống mạch li ti nào?", "answer": "Mao mạch"},
        {"id": "g7-wu-26", "text": "Thành phố Venice nổi tiếng với hệ thống kênh rạch chằng chịt nằm ở quốc gia châu Âu nào?", "answer": "Ý (Italia)"},
        {"id": "g7-wu-27", "text": "Lê Lợi đã trả lại gươm báu cho Rùa Vàng tại hồ nước nào ở trung tâm Hà Nội?", "answer": "Hồ Hoàn Kiếm (Hồ Gươm)"},
        {"id": "g7-wu-28", "text": "Hai đại lượng x và y liên hệ theo công thức y = k/x (với k khác 0) là quan hệ tỉ lệ gì?", "answer": "Tỉ lệ nghịch"},
        {"id": "g7-wu-29", "text": "Khi ánh sáng chiếu tới một bề mặt gương phẳng, góc hợp bởi tia tới và pháp tuyến gọi là góc gì?", "answer": "Góc tới"},
        {"id": "g7-wu-30", "text": "Hô hấp tế bào xảy ra chủ yếu ở bào quan nào để tạo ra năng lượng ATP cung cấp cho cơ thể?", "answer": "Ty thể"},
        {"id": "g7-wu-31", "text": "Độ to của âm thanh phụ thuộc chủ yếu vào đại lượng vật lý nào của nguồn âm?", "answer": "Biên độ dao động"},
        {"id": "g7-wu-32", "text": "Dãy núi trẻ nào cao nhất và đồ sộ nhất ở châu Âu?", "answer": "Dãy Alps (An-pơ)"},
        {"id": "g7-wu-33", "text": "Tổng ba góc trong một tam giác phẳng bất kỳ luôn bằng bao nhiêu độ?", "answer": "180 độ"},
        {"id": "g7-wu-34", "text": "Thành Tây Đô (Thành nhà Hồ) bằng đá độc đáo ở tỉnh Thanh Hóa do ai cho xây dựng?", "answer": "Hồ Quý Ly"},
        {"id": "g7-wu-35", "text": "Nguyên tố hóa học có ký hiệu là Fe trong bảng tuần hoàn tên tiếng Việt là gì?", "answer": "Sắt (Iron)"},
        {"id": "g7-wu-36", "text": "Hiện tượng thân cây uốn cong vươn về phía có nguồn ánh sáng được gọi là hiện tượng gì?", "answer": "Hướng sáng (tính hướng sáng)"},
        {"id": "g7-wu-37", "text": "Hai đường thẳng vuông góc với nhau tạo thành góc có số đo bằng bao nhiêu độ?", "answer": "90 độ"},
        {"id": "g7-wu-38", "text": "Văn bản nhật dụng nào phản ánh nỗi đau chia tay của hai anh em Thành và Thủy khi bố mẹ ly hôn?", "answer": "Cuộc chia tay của những con búp bê"},
        {"id": "g7-wu-39", "text": "Vận tốc truyền âm trong không khí ở 20 độ C xấp xỉ bằng bao nhiêu mét trên giây?", "answer": "Khoảng 340 m/s"},
        {"id": "g7-wu-40", "text": "Rừng rậm Taiga lá kim đặc trưng trải dài ở khu vực phía bắc của châu lục nào?", "answer": "Châu Á và Châu Âu (Bắc Á, Bắc Âu)"}
    ],
    "acceleration": [
        {"id": "g7-tt-6", "text": "Số nào sau đây là SỐ VÔ TỈ?", "options": ["3/4", "căn bậc hai của 2", "0,125", "-7"], "answer": "căn bậc hai của 2", "timeLimitSeconds": 20},
        {"id": "g7-tt-7", "text": "Nguyên tử của nguyên tố nào sau đây có số proton bằng 6 trong hạt nhân?", "options": ["Nitơ", "Oxi", "Cacbon", "Hiđro"], "answer": "Cacbon", "timeLimitSeconds": 20},
        {"id": "g7-tt-8", "text": "Một tia sáng chiếu tới gương phẳng với góc tới bằng 35 độ. Góc phản xạ là bao nhiêu độ?", "options": ["35 độ", "55 độ", "70 độ", "90 độ"], "answer": "35 độ", "timeLimitSeconds": 20},
        {"id": "g7-tt-9", "text": "Vị tướng chỉ huy quân Mông Cổ bị chém đầu trong trận Bạch Đằng năm 1288 là ai?", "options": ["Thoát Hoan", "Ô Mã Nhi", "Toa Đô", "Phàn Tiếp"], "answer": "Ô Mã Nhi", "timeLimitSeconds": 20},
        {"id": "g7-tt-10", "text": "Trong quá trình quang hợp, chất khí nào được cây xanh thải ra ngoài môi trường?", "options": ["Khí cacbonic", "Khí oxi", "Khí nitơ", "Khí metan"], "answer": "Khí oxi", "timeLimitSeconds": 20},
        {"id": "g7-tt-11", "text": "Cho tam giác ABC vuông tại A có AB = 6cm, AC = 8cm. Độ dài cạnh huyền BC là:", "options": ["10 cm", "14 cm", "12 cm", "7 cm"], "answer": "10 cm", "timeLimitSeconds": 20},
        {"id": "g7-tt-12", "text": "Tai người bình thường có thể nghe được dải âm thanh có tần số trong khoảng nào?", "options": ["Dưới 20 Hz", "Từ 20 Hz đến 20 000 Hz", "Trên 20 000 Hz", "Từ 100 Hz đến 1 000 Hz"], "answer": "Từ 20 Hz đến 20 000 Hz", "timeLimitSeconds": 20},
        {"id": "g7-tt-13", "text": "Đại lượng nào sau đây tỉ lệ thuận với khối lượng của một vật (ở cùng một vị trí trên Trái Đất)?", "options": ["Trọng lượng", "Thể tích", "Nhiệt độ", "Tốc độ"], "answer": "Trọng lượng", "timeLimitSeconds": 20},
        {"id": "g7-tt-14", "text": "Nhà thơ nào được mệnh danh là 'Bà Chúa Thơ Nôm' với những bài thơ trào lộng độc đáo?", "options": ["Đoàn Thị Điểm", "Hồ Xuân Hương", "Bà Huyện Thanh Quan", "Nguyễn Thị Lộ"], "answer": "Hồ Xuân Hương", "timeLimitSeconds": 20},
        {"id": "g7-tt-15", "text": "Trong cơ thể thực vật, dòng mạch rây có chức năng vận chuyển chất gì?", "options": ["Nước và chất khoáng", "Chất hữu cơ tổng hợp từ lá", "Khí oxi", "Khí cacbonic"], "answer": "Chất hữu cơ tổng hợp từ lá", "timeLimitSeconds": 20},
        {"id": "g7-tt-16", "text": "Giao điểm của ba đường cao trong một tam giác được gọi là gì?", "options": ["Trọng tâm", "Trực tâm", "Tâm đường tròn nội tiếp", "Tâm đường tròn ngoại tiếp"], "answer": "Trực tâm", "timeLimitSeconds": 20},
        {"id": "g7-tt-17", "text": "Quốc gia nào sau đây ở châu Phi có diện tích lớn nhất?", "options": ["Nigeria", "Algeria", "Ai Cập", "Nam Phi"], "answer": "Algeria", "timeLimitSeconds": 20},
        {"id": "g7-tt-18", "text": "Liên kết hóa học được hình thành do lực hút tĩnh điện giữa các ion mang điện tích trái dấu là liên kết gì?", "options": ["Liên kết ion", "Liên kết cộng hóa trị", "Liên kết kim loại", "Liên kết hiđro"], "answer": "Liên kết ion", "timeLimitSeconds": 20},
        {"id": "g7-tt-19", "text": "Âm thanh KHÔNG THỂ truyền qua môi trường nào sau đây?", "options": ["Nước biển", "Không khí", "Chân không", "Khối thép"], "answer": "Chân không", "timeLimitSeconds": 20},
        {"id": "g7-tt-20", "text": "Nếu y tỉ lệ thuận với x theo hệ số tỉ lệ k = 3 thì x tỉ lệ thuận với y theo hệ số tỉ lệ nào?", "options": ["3", "-3", "1/3", "-1/3"], "answer": "1/3", "timeLimitSeconds": 20},
        {"id": "g7-tt-21", "text": "Ai là người chỉ huy quân Tây Sơn mở cuộc hành quân thần tốc đánh tan 29 vạn quân Thanh vào dịp Tết Kỷ Dậu 1789?", "options": ["Nguyễn Nhạc", "Nguyễn Lữ", "Quang Trung (Nguyễn Huệ)", "Trần Quang Diệu"], "answer": "Quang Trung (Nguyễn Huệ)", "timeLimitSeconds": 20},
        {"id": "g7-tt-22", "text": "Hiện tượng tiếng vang xảy ra khi âm phản xạ đến tai cách âm trực tiếp một khoảng thời gian ít nhất là bao nhiêu?", "options": ["1/15 giây", "1/5 giây", "1 giây", "0,5 giây"], "answer": "1/15 giây", "timeLimitSeconds": 20},
        {"id": "g7-tt-23", "text": "Phép lai phân tích do nhà khoa học nào sáng tạo ra để kiểm tra kiểu gen của cá thể mang tính trạng trội?", "options": ["Darwin", "Mendel", "Morgan", "Pasteur"], "answer": "Mendel", "timeLimitSeconds": 20},
        {"id": "g7-tt-24", "text": "Đa thức P(x) = 2x^3 - 5x + 7 có bậc là bao nhiêu?", "options": ["1", "2", "3", "7"], "answer": "3", "timeLimitSeconds": 20},
        {"id": "g7-tt-25", "text": "Hoang mạc nhiệt đới nào lớn nhất thế giới nằm ở Bắc Phi?", "options": ["Hoang mạc Gobi", "Hoang mạc Sahara", "Hoang mạc Kalahari", "Hoang mạc Atacama"], "answer": "Hoang mạc Sahara", "timeLimitSeconds": 20},
        {"id": "g7-tt-26", "text": "Ảnh của một vật tạo bởi gương phẳng có tính chất gì?", "options": ["Là ảnh thật, bằng vật", "Là ảnh ảo, lớn hơn vật", "Là ảnh ảo, bằng vật", "Là ảnh thật, ngược chiều vật"], "answer": "Là ảnh ảo, bằng vật", "timeLimitSeconds": 20},
        {"id": "g7-tt-27", "text": "Nguyên tố nào sau đây là KHÍ HIẾM (khí trơ)?", "options": ["Oxi", "Neon", "Nitơ", "Clo"], "answer": "Neon", "timeLimitSeconds": 20},
        {"id": "g7-tt-28", "text": "Tam giác ABC có số đo góc A = 50 độ, góc B = 60 độ. Số đo của góc C là:", "options": ["70 độ", "80 độ", "90 độ", "60 độ"], "answer": "70 độ", "timeLimitSeconds": 20},
        {"id": "g7-tt-29", "text": "Thành ngữ nào sau đây mang ý nghĩa nói về tình cảm anh em gắn bó, đùm bọc nhau?", "options": ["Môi hở răng lạnh", "Cháy nhà ra mặt chuột", "Nước đổ đầu vịt", "Ăn cháo đá bát"], "answer": "Môi hở răng lạnh", "timeLimitSeconds": 20},
        {"id": "g7-tt-30", "text": "Cơ quan bài tiết chính ở động vật có xương sống và người là:", "options": ["Phổi", "Da", "Thận", "Gan"], "answer": "Thận", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g7-vd-10-4", "points": 10, "text": "Điểm cách đều ba đỉnh của một tam giác là giao điểm của ba đường gì trong tam giác?", "answer": "Ba đường trung trực"},
        {"id": "g7-vd-10-5", "points": 10, "text": "Tác phẩm kịch châm biếm kinh điển 'Trưởng giả học làm sang' là của nhà soạn kịch nổi tiếng người Pháp nào?", "answer": "Molière (Mô-li-e)"},
        {"id": "g7-vd-10-6", "points": 10, "text": "Hạt nhân của nguyên tử hầu hết được cấu tạo bởi hai loại hạt nào?", "answer": "Proton và nơtron"},
        {"id": "g7-vd-10-7", "points": 10, "text": "Tập hợp các số thực được ký hiệu bằng chữ cái in hoa nào?", "answer": "Ký hiệu R"},
        {"id": "g7-vd-10-8", "points": 10, "text": "Trận quyết chiến chiến lược nào trên sông Như Nguyệt năm 1077 đã đánh bại hoàn toàn quân xâm lược nhà Tống?", "answer": "Chiến trận phòng tuyến sông Như Nguyệt"},
        {"id": "g7-vd-10-9", "points": 10, "text": "Sóng âm có thể truyền được qua các môi trường chất rắn, chất lỏng và chất gì?", "answer": "Chất khí"},
        {"id": "g7-vd-10-10", "points": 10, "text": "Đỉnh núi Mont Blanc (Mông Băng) thuộc dãy núi Alps là đỉnh núi cao nhất của khu vực châu lục nào?", "answer": "Châu Âu"},
        {"id": "g7-vd-20-4", "points": 20, "text": "Tìm giá trị của x trong tỉ lệ thức: x / 6 = 15 / 10?", "answer": "x = 9"},
        {"id": "g7-vd-20-5", "points": 20, "text": "Vị thái sư nào thời Trần đã có câu nói khẳng khái nổi tiếng: 'Đầu thần chưa rơi xuống đất, xin bệ hạ đừng lo'?", "answer": "Trần Thủ Độ"},
        {"id": "g7-vd-20-6", "points": 20, "text": "Một người nhìn thấy tia sét rồi sau 3 giây mới nghe thấy tiếng sấm. Biết vận tốc truyền âm trong không khí là 340 m/s, hỏi khoảng cách từ người đó đến nơi phát ra tia sét là bao nhiêu mét?", "answer": "1020 mét"},
        {"id": "g7-vd-20-7", "points": 20, "text": "Một tam giác vuông cân có độ dài cạnh huyền là căn bậc hai của 50 cm. Độ dài mỗi cạnh góc vuông của tam giác đó là bao nhiêu cm?", "answer": "5 cm"},
        {"id": "g7-vd-20-8", "points": 20, "text": "Quá trình quang hợp của cây xanh hấp thụ nước và khí cacbonic dưới tác dụng của ánh sáng để tổng hợp nên chất hữu cơ chính là gì?", "answer": "Glucozơ (chất bột đường / Carbohydrate)"},
        {"id": "g7-vd-20-9", "points": 20, "text": "Kênh đào Suez nối liền hai biển nào của khu vực châu Á và châu Phi?", "answer": "Địa Trung Hải và Biển Đỏ"},
        {"id": "g7-vd-20-10", "points": 20, "text": "Bảng tuần hoàn các nguyên tố hóa học hiện đại do nhà hóa học vĩ đại người Nga nào phát minh và đặt nền móng?", "answer": "Dmitri Mendeleev"},
        {"id": "g7-vd-30-4", "points": 30, "text": "Cho tam giác ABC có ba góc A, B, C tỉ lệ với các số 1; 2; 3. Tính số đo góc lớn nhất của tam giác đó?", "answer": "90 độ"},
        {"id": "g7-vd-30-5", "points": 30, "text": "Ai là tác giả của áng thơ 'Nam quốc sơn hà' được cất lên thần kỳ trên sông Như Nguyệt làm khiếp đảm quân Tống?", "answer": "Lý Thường Kiệt"},
        {"id": "g7-vd-30-6", "points": 30, "text": "Chiếc gương phẳng đặt vuông góc với mặt đất, một người cao 1,6m đứng cách gương 2m. Khoảng cách giữa người đó và ảnh của mình qua gương là bao nhiêu mét?", "answer": "4 mét"},
        {"id": "g7-vd-30-7", "points": 30, "text": "Vật chất di truyền trong tế bào sinh vật nhân thực được lưu trữ dưới dạng đại phân tử sinh học nào có cấu trúc xoắn kép?", "answer": "Axit Deoxyribonucleic (ADN)"},
        {"id": "g7-vd-30-8", "points": 30, "text": "Cho đa thức P(x) = ax^2 + bx + c. Biết P(0) = 3; P(1) = 6; P(-1) = 2. Tính hệ số a của đa thức đó?", "answer": "a = 1"},
        {"id": "g7-vd-30-9", "points": 30, "text": "Người Tây Ban Nha nào đã chỉ huy đoàn thám hiểm vượt Đại Tây Dương và phát hiện ra châu Mỹ vào năm 1492?", "answer": "Christopher Columbus (Cơ-ri-xtô-phơ Cô-lôm-bô)"},
        {"id": "g7-vd-30-10", "points": 30, "text": "Tại sao khi gõ vào chiếc chuông đồng ta nghe thấy âm thanh phát ra, nhưng nếu đặt tay áp chặt vào thành chuông thì âm thanh ngay lập tức tắt lịm?", "answer": "Vì âm thanh sinh ra do dao động, khi giữ chặt tay thì chuông ngừng dao động nên âm tắt"}
    ]
}
