# -*- coding: utf-8 -*-
GRADE_11_DATA = {
    "warmup": [
        {"id": "g11-wu-6", "text": "Đạo hàm của hàm số y = sin x là hàm số nào?", "answer": "cos x"},
        {"id": "g11-wu-7", "text": "Định luật Coulomb xác định lực tương tác tĩnh điện giữa hai điện tích điểm tỉ lệ nghịch với bình phương của đại lượng nào?", "answer": "Khoảng cách giữa hai điện tích"},
        {"id": "g11-wu-8", "text": "Hợp chất hữu cơ chứa nhóm chức -CHO liên kết trực tiếp với nguyên tử cacbon hoặc hiđro thuộc loại hợp chất gì?", "answer": "Anđehit (Aldehyde)"},
        {"id": "g11-wu-9", "text": "Hình tượng nhân vật Huấn Cao với tài viết chữ đẹp và khí phách hiên ngang xuất hiện trong truyện ngắn nào của Nguyễn Tuân?", "answer": "Chữ người tử tù"},
        {"id": "g11-wu-10", "text": "Chu trình cố định CO2 ở thực vật C3 còn có tên gọi là chu trình gì?", "answer": "Chu trình Calvin (Can-vin)"},
        {"id": "g11-wu-11", "text": "Công sai d của một cấp số cộng có u1 = 3 và u2 = 7 bằng bao nhiêu?", "answer": "d = 4"},
        {"id": "g11-wu-12", "text": "Nguyên lý Le Chatelier nêu: Khi một hệ cân bằng hóa học bị tác động từ bên ngoài thì cân bằng sẽ chuyển dịch theo chiều nào?", "answer": "Chiều chống lại tác động bên ngoài đó"},
        {"id": "g11-wu-13", "text": "Đơn vị đo độ tự cảm của ống dây trong hệ SI là gì?", "answer": "Henry (H)"},
        {"id": "g11-wu-14", "text": "Hai mặt phẳng vuông góc với nhau khi góc giữa hai mặt phẳng đó bằng bao nhiêu độ?", "answer": "90 độ"},
        {"id": "g11-wu-15", "text": "Bài thơ 'Vội vàng' với triết lý sống khát khao tận hưởng từng giây phút tuổi trẻ là của thi sĩ nào?", "answer": "Xuân Diệu"},
        {"id": "g11-wu-16", "text": "Huyết áp ở người đo được tại động mạch cánh tay cao nhất ở thời điểm nào của hoạt động tim?", "answer": "Thời điểm tâm thất co (huyết áp tâm thu)"},
        {"id": "g11-wu-17", "text": "Axit nitric (HNO3) đặc, nguội làm thụ động hóa hai kim loại phổ biến nào?", "answer": "Nhôm (Al) và Sắt (Fe)"},
        {"id": "g11-wu-18", "text": "Phương trình dao động điều hòa x = A.cos(ωt + φ) có đại lượng A biểu thị cho yếu tố gì?", "answer": "Biên độ dao động"},
        {"id": "g11-wu-19", "text": "Tổ chức liên minh chính trị - kinh tế khu vực lớn nhất thế giới gồm 27 quốc gia châu Âu có tên viết tắt là gì?", "answer": "EU (Liên minh Châu Âu)"},
        {"id": "g11-wu-20", "text": "Giới hạn của dãy số (1/n) khi n tiến ra vô cùng bằng bao nhiêu?", "answer": "0"},
        {"id": "g11-wu-21", "text": "Nhóm hợp chất thơm đơn giản nhất có công thức phân tử C6H6 tên là gì?", "answer": "Benzen"},
        {"id": "g11-wu-22", "text": "Khúc xạ ánh sáng xảy ra hiện tượng phản xạ toàn phần khi góc tới i lớn hơn hoặc bằng góc nào?", "answer": "Góc giới hạn phản xạ toàn phần (i_gh)"},
        {"id": "g11-wu-23", "text": "Đoạn trích 'Hạnh phúc của một tang gia' trích từ tiểu thuyết trào phúng kiệt xuất nào của Vũ Trọng Phụng?", "answer": "Số đỏ"},
        {"id": "g11-wu-24", "text": "Hình thức thụ tinh trong đó trứng và tinh trùng kết hợp bên ngoài cơ thể con cái (trong môi trường nước) gọi là gì?", "answer": "Thụ tinh ngoài"},
        {"id": "g11-wu-25", "text": "Công thức tính số hạng tổng quát un của cấp số nhân theo u1 và công bội q là gì?", "answer": "un = u1 . q^(n-1)"},
        {"id": "g11-wu-26", "text": "Chất khí nào có mùi khai đặc trưng, tan rất nhiều trong nước tạo thành dung dịch bazơ yếu?", "answer": "Khí amoniac (NH3)"},
        {"id": "g11-wu-27", "text": "Định luật Ohm cho toàn mạch kín xác định cường độ dòng điện I bằng tỉ số giữa suất điện động E và đại lượng nào?", "answer": "Tổng trở toàn mạch (R_ngoài + r_trong)"},
        {"id": "g11-wu-28", "text": "Thơ mới giai đoạn 1932 - 1945 mở đầu bằng bài thơ nổi tiếng 'Tình già' của tác giả nào?", "answer": "Phan Khôi"},
        {"id": "g11-wu-29", "text": "Quá trình thoát hơi nước ở lá cây chủ yếu diễn ra qua cấu trúc nào?", "answer": "Khí khổng"},
        {"id": "g11-wu-30", "text": "Quốc gia nào ở Đông Bắc Á có diện tích rộng lớn thứ tư thế giới và dân số đông trên 1,4 tỉ người?", "answer": "Trung Quốc"},
        {"id": "g11-wu-31", "text": "Đạo hàm cấp một của hàm số y = x^3 - 3x tại x = 2 bằng bao nhiêu?", "answer": "9"},
        {"id": "g11-wu-32", "text": "Hợp chất phenol (C6H5OH) tác dụng với nước brom sinh ra kết tủa màu gì?", "answer": "Kết tủa trắng (2,4,6-tribromphenol)"},
        {"id": "g11-wu-33", "text": "Hạt tải điện trong kim loại là hạt gì?", "answer": "Electron tự do"},
        {"id": "g11-wu-34", "text": "Cuộc Cách mạng tháng Mười Nga năm 1917 do ai lãnh đạo dưới ngọn cờ của Đảng Bolshevik?", "answer": "V. I. Lênin"},
        {"id": "g11-wu-35", "text": "Hormone auxin ở thực vật có vai trò chính kích thích quá trình gì của tế bào?", "answer": "Kéo dài tế bào (sinh trưởng tế bào)"},
        {"id": "g11-wu-36", "text": "Khoảng cách giữa hai đường thẳng chéo nhau là độ dài đoạn thẳng vuông góc gì của hai đường thẳng đó?", "answer": "Đoạn vuông góc chung"},
        {"id": "g11-wu-37", "text": "Theo thuyết Bronsted - Lowry, axit là chất có khả năng nhường hạt gì?", "answer": "Proton (H+)"},
        {"id": "g11-wu-38", "text": "Tác phẩm 'Đây thôn Vĩ Dạ' gắn liền với mối tình đơn phương kín đáo của nhà thơ tài hoa bạc mệnh nào?", "answer": "Hàn Mặc Tử"},
        {"id": "g11-wu-39", "text": "Khu vực Đông Nam Á hiện nay gồm có bao nhiêu quốc gia độc lập?", "answer": "11 quốc gia"},
        {"id": "g11-wu-40", "text": "Lực từ tác dụng lên một hạt mang điện chuyển động trong từ trường được gọi là lực gì?", "answer": "Lực Lorentz (Lo-ren-xơ)"}
    ],
    "acceleration": [
        {"id": "g11-tt-6", "text": "Nghiệm của phương trình lượng giác: sin x = 1/2 là:", "options": ["x = pi/6 + k2pi và x = 5pi/6 + k2pi", "x = pi/3 + k2pi và x = 2pi/3 + k2pi", "x = pi/6 + kpi", "x = -pi/6 + k2pi"], "answer": "x = pi/6 + k2pi và x = 5pi/6 + k2pi", "timeLimitSeconds": 20},
        {"id": "g11-tt-7", "text": "Dung dịch có nồng độ ion H+ là [H+] = 10^-3 M thì có chỉ số pH bằng bao nhiêu?", "options": ["3", "11", "7", "-3"], "answer": "3", "timeLimitSeconds": 20},
        {"id": "g11-tt-8", "text": "Một tụ điện có điện dung C = 20 microfarad được tích điện dưới hiệu điện thế U = 100V. Điện tích của tụ điện là:", "options": ["0,002 C", "2000 C", "0,2 C", "5 C"], "answer": "0,002 C", "timeLimitSeconds": 20},
        {"id": "g11-tt-9", "text": "Ở động vật nhai lại như trâu, bò, dạ dày gồm có mấy ngăn?", "options": ["4 ngăn", "3 ngăn", "2 ngăn", "1 ngăn"], "answer": "4 ngăn", "timeLimitSeconds": 20},
        {"id": "g11-tt-10", "text": "Ai là tác giả của áng văn chính luận bất hủ 'Tuyên ngôn Độc lập' của nước Mỹ năm 1776?", "options": ["Thomas Jefferson", "George Washington", "Benjamin Franklin", "Abraham Lincoln"], "answer": "Thomas Jefferson", "timeLimitSeconds": 20},
        {"id": "g11-tt-11", "text": "Giới hạn lim (2n^2 + 3) / (n^2 - n + 1) khi n tiến ra dương vô cùng bằng bao nhiêu?", "options": ["2", "3", "0", "vô cùng"], "answer": "2", "timeLimitSeconds": 20},
        {"id": "g11-tt-12", "text": "Ancol etylic (C2H5OH) đun nóng với H2SO4 đặc ở 170 độ C xảy ra phản ứng tách nước tạo thành chất khí nào?", "options": ["Etilen (C2H4)", "Đietyl ete", "Metan (CH4)", "Axetilen (C2H2)"], "answer": "Etilen (C2H4)", "timeLimitSeconds": 20},
        {"id": "g11-tt-13", "text": "Gia tốc của một vật dao động điều hòa luôn hướng về đâu?", "options": ["Vị trí cân bằng", "Vị trí biên dương", "Vị trí biên âm", "Theo hướng chuyển động"], "answer": "Vị trí cân bằng", "timeLimitSeconds": 20},
        {"id": "g11-tt-14", "text": "Hình tượng nhân vật Chí Phèo trước khi rơi vào bước đường cùng tha hóa vốn là một người nông dân như thế nào?", "options": ["Lương thiện, giàu lòng tự trọng", "Côn đồ, bất hảo", "Gian manh, tham lam", "Bạc nhược, hèn yếu"], "answer": "Lương thiện, giàu lòng tự trọng", "timeLimitSeconds": 20},
        {"id": "g11-tt-15", "text": "Cho tứ diện đều ABCD. Góc giữa hai đường thẳng đối diện AB và CD bằng bao nhiêu độ?", "options": ["90 độ", "60 độ", "45 độ", "30 độ"], "answer": "90 độ", "timeLimitSeconds": 20},
        {"id": "g11-tt-16", "text": "Hóa chất nào sau đây thường được dùng để khử chua đất nông nghiệp trồng trọt?", "options": ["Vôi tôi Ca(OH)2 hoặc vôi sống CaO", "Muối ăn NaCl", "Phân đạm ure", "Axit sunfuric H2SO4"], "answer": "Vôi tôi Ca(OH)2 hoặc vôi sống CaO", "timeLimitSeconds": 20},
        {"id": "g11-tt-17", "text": "Suất điện động cảm ứng trong mạch tỉ lệ với đại lượng nào theo định luật Faraday?", "options": ["Tốc độ biến thiên từ thông", "Độ lớn từ thông", "Cường độ dòng điện", "Điện trở của mạch"], "answer": "Tốc độ biến thiên từ thông", "timeLimitSeconds": 20},
        {"id": "g11-tt-18", "text": "Hệ tuần hoàn hở có đặc điểm nào sau đây so với hệ tuần hoàn kín?", "options": ["Máu chảy trong động mạch dưới áp lực thấp và tốc độ chậm", "Máu chảy trong mao mạch với áp lực cao", "Máu không tiếp xúc trực tiếp với các tế bào", "Có hai vòng tuần hoàn"], "answer": "Máu chảy trong động mạch dưới áp lực thấp và tốc độ chậm", "timeLimitSeconds": 20},
        {"id": "g11-tt-19", "text": "Liên bang Nga là quốc gia có đường bờ biển tiếp giáp với mấy đại dương trên thế giới?", "options": ["3 đại dương", "2 đại dương", "4 đại dương", "1 đại dương"], "answer": "3 đại dương", "timeLimitSeconds": 20},
        {"id": "g11-tt-20", "text": "Đạo hàm của hàm số y = tan x là:", "options": ["1 / (cos x)^2", "-1 / (sin x)^2", "cos x", "1 / (sin x)^2"], "answer": "1 / (cos x)^2", "timeLimitSeconds": 20},
        {"id": "g11-tt-21", "text": "Số đồng phân cấu tạo mạch hở ứng với công thức phân tử C4H10 (butan) là:", "options": ["2 đồng phân", "3 đồng phân", "4 đồng phân", "1 đồng phân"], "answer": "2 đồng phân", "timeLimitSeconds": 20},
        {"id": "g11-tt-22", "text": "Chiếu một tia sáng từ nước ra không khí với góc tới i = 60 độ. Biết chiết suất của nước n = 4/3. Hiện tượng gì sẽ xảy ra?", "options": ["Phản xạ toàn phần", "Khúc xạ với góc r < 60 độ", "Khúc xạ với góc r = 90 độ", "Tán sắc ánh sáng"], "answer": "Phản xạ toàn phần", "timeLimitSeconds": 20},
        {"id": "g11-tt-23", "text": "Bài thơ 'Tràng giang' của Huy Cận mang vẻ đẹp giao thoa giữa nét cổ điển Đường thi và nét gì hiện đại?", "options": ["Nỗi buồn bơ vơ của cái tôi lãng mạn Thơ mới", "Tinh thần chiến đấu sôi nổi", "Hứng khởi xây dựng đất nước", "Tính hiện thực phê phán gay gắt"], "answer": "Nỗi buồn bơ vơ của cái tôi lãng mạn Thơ mới", "timeLimitSeconds": 20},
        {"id": "g11-tt-24", "text": "Synap hóa học truyền xung thần kinh giữa hai nơron qua khe synap nhờ chất gì?", "options": ["Chất môi giới trung gian hóa học (như axetylcholin)", "Dòng electron tự do", "Xung ánh sáng", "Sóng siêu âm"], "answer": "Chất môi giới trung gian hóa học (như axetylcholin)", "timeLimitSeconds": 20},
        {"id": "g11-tt-25", "text": "Cuộc Minh Trị Duy Tân (1868) đã đưa nước Nhật Bản phát triển theo con đường nào?", "options": ["Chủ nghĩa tư bản", "Xã hội chủ nghĩa", "Phong kiến tập quyền", "Thuộc địa nửa phong kiến"], "answer": "Chủ nghĩa tư bản", "timeLimitSeconds": 20},
        {"id": "g11-tt-26", "text": "Tổng các góc phẳng nhị diện của một hình lập phương bằng bao nhiêu độ?", "options": ["Mỗi góc bằng 90 độ", "Mỗi góc bằng 60 độ", "Mỗi góc bằng 45 độ", "Mỗi góc bằng 120 độ"], "answer": "Mỗi góc bằng 90 độ", "timeLimitSeconds": 20},
        {"id": "g11-tt-27", "text": "Chất nào sau đây tác dụng được với dung dịch AgNO3 trong NH3 tạo kết tủa màu vàng nhạt?", "options": ["Axetilen (C2H2)", "Etilen (C2H4)", "Metan (CH4)", "Benzen (C6H6)"], "answer": "Axetilen (C2H2)", "timeLimitSeconds": 20},
        {"id": "g11-tt-28", "text": "Một con lắc lò xo gồm vật nặng khối lượng m và lò xo có độ cứng k dao động điều hòa với chu kỳ T bằng:", "options": ["2.pi . căn(m/k)", "2.pi . căn(k/m)", "1/(2.pi) . căn(m/k)", "2.pi . căn(g/l)"], "answer": "2.pi . căn(m/k)", "timeLimitSeconds": 20},
        {"id": "g11-tt-29", "text": "Thực vật CAM (như xương rồng, dứa) thích nghi với môi trường khô hạn bằng cách:", "options": ["Mở khí khổng ban đêm và đóng khí khổng ban ngày", "Đóng khí khổng ban đêm và mở ban ngày", "Không bao giờ mở khí khổng", "Lá biến đổi thành hoa"], "answer": "Mở khí khổng ban đêm và đóng khí khổng ban ngày", "timeLimitSeconds": 20},
        {"id": "g11-tt-30", "text": "Quốc gia nào sau đây là thành viên sáng lập Hiệp hội các quốc gia Đông Nam Á (ASEAN) năm 1967?", "options": ["Thái Lan", "Việt Nam", "Lào", "Campuchia"], "answer": "Thái Lan", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g11-vd-10-4", "points": 10, "text": "Hệ số góc k của tiếp tuyến với đồ thị hàm số y = f(x) tại điểm có hoành độ x0 là gì?", "answer": "k = f'(x0) (đạo hàm tại x0)"},
        {"id": "g11-vd-10-5", "points": 10, "text": "Công thức tính điện năng tiêu thụ A của một đoạn mạch có hiệu điện thế U, cường độ dòng điện I trong thời gian t là gì?", "answer": "A = U . I . t"},
        {"id": "g11-vd-10-6", "points": 10, "text": "Phản ứng este hóa giữa axit axetic và rượu etylic tạo ra este có mùi thơm đặc trưng tên là gì?", "answer": "Etyl axetat"},
        {"id": "g11-vd-10-7", "points": 10, "text": "Nhân vật người quản ngục trong truyện ngắn 'Chữ người tử tù' có sở thích cao quý nào?", "answer": "Sở nguyện xin chữ Huấn Cao (thú chơi chữ đẹp)"},
        {"id": "g11-vd-10-8", "points": 10, "text": "Nhóm thực vật nào sau đây gồm ngô, mía, cao lương có hiệu suất quang hợp cao hơn thực vật C3?", "answer": "Thực vật C4"},
        {"id": "g11-vd-10-9", "points": 10, "text": "Đồng tiền chung châu Âu được phát hành chính thức đưa vào lưu hành từ năm 2002 có tên là gì?", "answer": "Đồng Euro (Ơ-rô)"},
        {"id": "g11-vd-10-10", "points": 10, "text": "Phong trào Đông Du đưa thanh niên Việt Nam sang Nhật Bản học tập do nhà yêu nước nào khởi xướng năm 1905?", "answer": "Phan Bội Châu"},
        {"id": "g11-vd-20-4", "points": 20, "text": "Cho một cấp số cộng có u1 = 2 và công sai d = 5. Tính tổng S10 của 10 số hạng đầu tiên của cấp số cộng đó?", "answer": "245"},
        {"id": "g11-vd-20-5", "points": 20, "text": "Một nguồn điện có suất điện động E = 12V, điện trở trong r = 1 ôm nối với mạch ngoài gồm điện trở R = 5 ôm. Tính cường độ dòng điện chạy trong mạch kín?", "answer": "2 A"},
        {"id": "g11-vd-20-6", "points": 20, "text": "Khí hiđroclorua (HCl) tan nhiều trong nước tạo thành dung dịch axit clohiđric. Tính thể tích khí HCl (đktc) hòa tan trong 1 lít nước tạo dung dịch nồng độ 1M?", "answer": "22,4 lít"},
        {"id": "g11-vd-20-7", "points": 20, "text": "Hình tượng thiên nhiên mùa xuân xứ Huế trong thi phẩm 'Mùa xuân nho nhỏ' gắn liền với màu sắc của bông hoa nào?", "answer": "Bông hoa tím biếc"},
        {"id": "g11-vd-20-8", "points": 20, "text": "Cơ chế hình thành điện thế nghỉ ở tế bào thần kinh chủ yếu do sự chênh lệch nồng độ của hai ion kim loại nào giữa hai bên màng tế bào?", "answer": "Ion Natri (Na+) và Kali (K+)"},
        {"id": "g11-vd-20-9", "points": 20, "text": "Thung lũng Silicon (Silicon Valley) nổi tiếng là trung tâm công nghệ cao hàng đầu thế giới nằm ở bang nào của Hoa Kỳ?", "answer": "Bang California"},
        {"id": "g11-vd-20-10", "points": 20, "text": "Vị thủ lĩnh nghĩa quân nào đã hy sinh oanh liệt với câu nói nổi tiếng 'Bao giờ người Tây nhổ hết cỏ nước Nam thì mới hết người Nam đánh Tây'?", "answer": "Nguyễn Trung Trực"},
        {"id": "g11-vd-30-4", "points": 30, "text": "Cho hình chóp S.ABC có đáy ABC là tam giác vuông tại B, SA vuông góc với mặt phẳng đáy (ABC). Hỏi có bao nhiêu mặt bên của hình chóp là các tam giác vuông?", "answer": "Cả 3 mặt bên (SAB, SAC, SBC đều là tam giác vuông)"},
        {"id": "g11-vd-30-5", "points": 30, "text": "Một con lắc lò xo dao động điều hòa tự do. Biết động năng của con lắc bằng 3 lần thế năng khi li độ x bằng bao nhiêu phần của biên độ A?", "answer": "x = ± A / 2"},
        {"id": "g11-vd-30-6", "points": 30, "text": "Đốt cháy hoàn toàn một ankan X thu được 6,72 lít khí CO2 (đktc) và 7,2 gam H2O. Xác định công thức phân tử của ankan X?", "answer": "C3H8 (Propan)"},
        {"id": "g11-vd-30-7", "points": 30, "text": "Vở kịch lịch sử nổi tiếng 'Vũ Như Tô' của Nguyễn Huy Tưởng đặt ra mâu thuẫn sâu sắc giữa khát vọng nghệ thuật siêu đẳng muôn đời và điều gì của nhân dân lao động?", "answer": "Quyền lợi và đời sống cơ cực trước mắt của nhân dân"},
        {"id": "g11-vd-30-8", "points": 30, "text": "Tập tính bẩm sinh ở động vật được di truyền từ bố mẹ có bản chất sinh học là chuỗi các phản xạ thuộc loại nào?", "answer": "Phản xạ không điều kiện"},
        {"id": "g11-vd-30-9", "points": 30, "text": "Tổ chức Hiệp ước Bắc Đại Tây Dương (NATO) do Mỹ và các nước Tây Âu thành lập vào năm nào trong thời kỳ đầu Chiến tranh Lạnh?", "answer": "Năm 1949"},
        {"id": "g11-vd-30-10", "points": 30, "text": "Cho hai biến cố A và B độc lập với nhau. Biết xác suất P(A) = 0,4 và P(B) = 0,5. Tính xác suất để cả hai biến cố A và B cùng xảy ra P(A ∩ B)?", "answer": "0,2"}
    ]
}
