# -*- coding: utf-8 -*-
GRADE_10_DATA = {
    "warmup": [
        {"id": "g10-wu-6", "text": "Hạt proton và hạt nơtron trong hạt nhân nguyên tử đều được cấu tạo từ các hạt cơ bản nhỏ hơn gọi là gì?", "answer": "Quark (hạt quác)"},
        {"id": "g10-wu-7", "text": "Định luật I Newton về chuyển động của vật còn có tên gọi phổ biến trong đời sống là gì?", "answer": "Định luật quán tính"},
        {"id": "g10-wu-8", "text": "Công thức tính diện tích tam giác theo ba cạnh a, b, c và nửa chu vi p được mang tên nhà toán học cổ đại nào?", "answer": "Công thức Heron (Hê-rông)"},
        {"id": "g10-wu-9", "text": "Bào quan nào trong tế bào thực vật chứa sắc tố quang hợp hấp thụ ánh sáng mặt trời?", "answer": "Lục lạp"},
        {"id": "g10-wu-10", "text": "Đoạn trích 'Chiến thắng Mtao Mxây' là trích đoạn nổi tiếng thuộc sử thi nào của đồng bào Tây Nguyên?", "answer": "Sử thi Đăm Săn"},
        {"id": "g10-wu-11", "text": "Nguyên tố nào có độ âm điện lớn nhất trong bảng tuần hoàn các nguyên tố hóa học?", "answer": "Flo (Fluorine, ký hiệu F)"},
        {"id": "g10-wu-12", "text": "Vectơ có điểm đầu trùng với điểm cuối được gọi là vectơ gì?", "answer": "Vectơ-không (vectơ 0)"},
        {"id": "g10-wu-13", "text": "Hiện tượng một vật tiếp tục chuyển động tròn quanh một trục do lực nào gây ra hướng về phía tâm quỹ đạo?", "answer": "Lực hướng tâm"},
        {"id": "g10-wu-14", "text": "Đơn vị tiền tệ của các tế bào sinh vật dùng để dự trữ và giải phóng năng lượng nhanh chóng là phân tử gì?", "answer": "ATP (Adenosine triphosphate)"},
        {"id": "g10-wu-15", "text": "Nền văn minh Chăm-pa cổ để lại quần thể đền tháp bằng gạch nung nổi tiếng ở tỉnh Quảng Nam tên là gì?", "answer": "Thánh địa Mỹ Sơn"},
        {"id": "g10-wu-16", "text": "Số orbital (obitan) nguyên tử tối đa trong phân lớp p là bao nhiêu?", "answer": "3 orbital"},
        {"id": "g10-wu-17", "text": "Gia tốc rơi tự do của các vật ở gần bề mặt Trái Đất thường được lấy giá trị xấp xỉ bằng bao nhiêu m/s2?", "answer": "9,8 m/s2 (hoặc 10 m/s2)"},
        {"id": "g10-wu-18", "text": "Biểu thức tọa độ của tích vô hướng của hai vectơ u(x1; y1) và v(x2; y2) là gì?", "answer": "x1.x2 + y1.y2"},
        {"id": "g10-wu-19", "text": "Bài thơ chữ Hán 'Thuật hoài' (Bày tỏ nỗi lòng) nổi tiếng với câu mở đầu 'Hoành sóc giang sơn kháp kỷ thu' do vị tướng nào thời Trần sáng tác?", "answer": "Phạm Ngũ Lão"},
        {"id": "g10-wu-20", "text": "Quá trình đường phân trong hô hấp tế bào biến đổi 1 phân tử glucozơ thành 2 phân tử axit nào?", "answer": "Axit pyruvic (Pyruvate)"},
        {"id": "g10-wu-21", "text": "Loại liên kết hóa học hình thành do dùng chung các cặp electron giữa hai nguyên tử gọi là liên kết gì?", "answer": "Liên kết cộng hóa trị"},
        {"id": "g10-wu-22", "text": "Đại lượng vật lý bằng tích của khối lượng và vận tốc của một vật đang chuyển động gọi là gì?", "answer": "Động lượng (p = m.v)"},
        {"id": "g10-wu-23", "text": "Tập hợp rỗng là tập hợp có bao nhiêu phần tử?", "answer": "0 phần tử (không có phần tử nào)"},
        {"id": "g10-wu-24", "text": "Văn minh Phù Nam cổ gắn liền với di chỉ khảo cổ học nổi tiếng nào ở vùng đồng bằng sông Cửu Long?", "answer": "Di chỉ Óc Eo (An Giang)"},
        {"id": "g10-wu-25", "text": "Hai lực cân bằng là hai lực cùng tác dụng vào một vật, cùng giá, ngược chiều và có tính chất gì về độ lớn?", "answer": "Cùng độ lớn"},
        {"id": "g10-wu-26", "text": "Đơn phân cấu tạo nên đại phân tử sinh học protein là các phân tử gì?", "answer": "Axit amin (Amino acid)"},
        {"id": "g10-wu-27", "text": "Phản ứng hóa học có biến thiên enthalpy chuẩn Delta r H° < 0 là phản ứng tỏa nhiệt hay thu nhiệt?", "answer": "Phản ứng tỏa nhiệt"},
        {"id": "g10-wu-28", "text": "Đồ thị của hàm số bậc hai y = ax^2 + bx + c (a khác 0) trong mặt phẳng tọa độ là đường gì?", "answer": "Đường parabol"},
        {"id": "g10-wu-29", "text": "Vở chèo cổ nổi tiếng của Việt Nam với trích đoạn 'Xúy Vân giả dại' có tên là gì?", "answer": "Kim Nham"},
        {"id": "g10-wu-30", "text": "Lực hút tĩnh điện yếu giữa các phân tử do sự phân cực tạm thời được gọi là tương tác gì?", "answer": "Tương tác van der Waals"},
        {"id": "g10-wu-31", "text": "Thời gian Trái Đất chuyển động trọn vẹn một vòng quanh Mặt Trời là khoảng bao nhiêu ngày?", "answer": "365 ngày và 6 giờ (365,25 ngày)"},
        {"id": "g10-wu-32", "text": "Cơ năng của một vật chuyển động chỉ dưới tác dụng của trọng lực là tổng của động năng và đại lượng nào?", "answer": "Thế năng trọng trường"},
        {"id": "g10-wu-33", "text": "Cấu trúc vỏ protein bao bọc bên ngoài lõi axit nucleic của hạt virus gọi là gì?", "answer": "Vỏ capsid"},
        {"id": "g10-wu-34", "text": "Trong tam giác ABC, định lý Cosin cho cạnh a có công thức: a^2 = b^2 + c^2 trừ đi biểu thức nào?", "answer": "2bc.cos A"},
        {"id": "g10-wu-35", "text": "Nhà nước phong kiến Đại Việt chính thức đổi quốc hiệu từ Đại Cồ Việt sang Đại Việt dưới thời vua nào vào năm 1054?", "answer": "Vua Lý Thánh Tông"},
        {"id": "g10-wu-36", "text": "Hiện tượng các electron hóa trị chuyển động tự do trong toàn bộ mạng tinh thể kim loại tạo nên liên kết gì?", "answer": "Liên kết kim loại"},
        {"id": "g10-wu-37", "text": "Đại lượng đo tốc độ sinh công của lực trong một đơn vị thời gian gọi là gì?", "answer": "Công suất"},
        {"id": "g10-wu-38", "text": "Giai đoạn nào trong chu kỳ tế bào diễn ra sự nhân đôi ADN và nhiễm sắc thể?", "answer": "Pha S (kỳ trung gian)"},
        {"id": "g10-wu-39", "text": "Số cách chọn k phần tử từ một tập hợp n phần tử (không phân biệt thứ tự chọn) gọi là gì?", "answer": "Tổ hợp chập k của n (C_n^k)"},
        {"id": "g10-wu-40", "text": "Gió mùa mùa hạ ở miền Nam nước ta và Đông Nam Á có tính chất nóng ẩm hay lạnh khô?", "answer": "Nóng ẩm và mưa nhiều"}
    ],
    "acceleration": [
        {"id": "g10-tt-6", "text": "Cho tam giác ABC có AB = 5, AC = 8 và góc A = 60 độ. Độ dài cạnh BC bằng bao nhiêu?", "options": ["7", "căn 65", "căn 89", "6"], "answer": "7", "timeLimitSeconds": 20},
        {"id": "g10-tt-7", "text": "Cấu hình electron nguyên tử của nguyên tố Clo (Z = 17) ở trạng thái cơ bản là:", "options": ["1s2 2s2 2p6 3s2 3p5", "1s2 2s2 2p6 3s2 3p6", "1s2 2s2 2p6 3s1 3p6", "1s2 2s2 2p5 3s2 3p6"], "answer": "1s2 2s2 2p6 3s2 3p5", "timeLimitSeconds": 20},
        {"id": "g10-tt-8", "text": "Một ô tô có khối lượng 1000 kg đang chuyển động với vận tốc 20 m/s. Động năng của ô tô là:", "options": ["200 000 J", "400 000 J", "100 000 J", "20 000 J"], "answer": "200 000 J", "timeLimitSeconds": 20},
        {"id": "g10-tt-9", "text": "Lipid nào sau đây là thành phần chính cấu tạo nên lớp màng kép của màng sinh chất tế bào?", "options": ["Phospholipid", "Triglyceride", "Steroid", "Sáp"], "answer": "Phospholipid", "timeLimitSeconds": 20},
        {"id": "g10-tt-10", "text": "Văn minh Văn Lang - Âu Lạc phát triển trên cơ sở nền văn hóa khảo cổ học nào?", "options": ["Văn hóa Đông Sơn", "Văn hóa Sa Huỳnh", "Văn hóa Đồng Nai", "Văn hóa Hòa Bình"], "answer": "Văn hóa Đông Sơn", "timeLimitSeconds": 20},
        {"id": "g10-tt-11", "text": "Tọa độ đỉnh I của parabol y = x^2 - 4x + 3 là:", "options": ["I(2; -1)", "I(-2; 15)", "I(2; 3)", "I(-2; -1)"], "answer": "I(2; -1)", "timeLimitSeconds": 20},
        {"id": "g10-tt-12", "text": "Trong phản ứng: Fe + 2HCl -> FeCl2 + H2, nguyên tử Fe đóng vai trò là:", "options": ["Chất khử", "Chất oxi hóa", "Chất tạo môi trường", "Chất xúc tác"], "answer": "Chất khử", "timeLimitSeconds": 20},
        {"id": "g10-tt-13", "text": "Một vật ném ngang từ độ cao h = 20m với vận tốc đầu v0 = 15 m/s (lấy g = 10 m/s2). Tầm bay xa của vật là:", "options": ["30 m", "45 m", "20 m", "60 m"], "answer": "30 m", "timeLimitSeconds": 20},
        {"id": "g10-tt-14", "text": "Kỳ nào của quá trình nguyên phân các nhiễm sắc thể co xoắn cực đại và xếp thành một hàng trên mặt phẳng xích đạo?", "options": ["Kỳ đầu", "Kỳ giữa", "Kỳ sau", "Kỳ cuối"], "answer": "Kỳ giữa", "timeLimitSeconds": 20},
        {"id": "g10-tt-15", "text": "Thơ Đường luật thất ngôn bát cú có tổng cộng bao nhiêu câu và bao nhiêu chữ trong toàn bài?", "options": ["8 câu, 56 chữ", "4 câu, 28 chữ", "8 câu, 64 chữ", "6 câu, 48 chữ"], "answer": "8 câu, 56 chữ", "timeLimitSeconds": 20},
        {"id": "g10-tt-16", "text": "Phương trình đường tròn có tâm I(1; -2) và bán kính R = 3 là:", "options": ["(x - 1)^2 + (y + 2)^2 = 9", "(x + 1)^2 + (y - 2)^2 = 9", "(x - 1)^2 + (y + 2)^2 = 3", "(x + 1)^2 + (y - 2)^2 = 3"], "answer": "(x - 1)^2 + (y + 2)^2 = 9", "timeLimitSeconds": 20},
        {"id": "g10-tt-17", "text": "Yếu tố nào sau đây KHÔNG LÀM THAY ĐỔI tốc độ của phản ứng hóa học?", "options": ["Nồng độ chất phản ứng", "Nhiệt độ", "Chất xúc tác", "Khối lượng sản phẩm thu được"], "answer": "Khối lượng sản phẩm thu được", "timeLimitSeconds": 20},
        {"id": "g10-tt-18", "text": "Lực căng của sợi dây treo một vật đứng yên cân bằng với lực nào?", "options": ["Trọng lực tác dụng lên vật", "Lực ma sát", "Lực hướng tâm", "Lực quán tính"], "answer": "Trọng lực tác dụng lên vật", "timeLimitSeconds": 20},
        {"id": "g10-tt-19", "text": "Tế bào nhân sơ khác tế bào nhân thực ở điểm căn bản nào?", "options": ["Chưa có màng nhân bao bọc vật chất di truyền", "Không có ADN", "Không có màng sinh chất", "Kích thước lớn hơn"], "answer": "Chưa có màng nhân bao bọc vật chất di truyền", "timeLimitSeconds": 20},
        {"id": "g10-tt-20", "text": "Vua nào thời phong kiến nước ta đã mở kỳ thi Thái học sinh đầu tiên để tuyển chọn nhân tài vào năm 1075?", "options": ["Lý Nhân Tông", "Lý Thái Tổ", "Trần Thái Tông", "Lê Thánh Tông"], "answer": "Lý Nhân Tông", "timeLimitSeconds": 20},
        {"id": "g10-tt-21", "text": "Có bao nhiêu cách sắp xếp 5 bạn học sinh ngồi vào một bàn dài có 5 chỗ ngồi?", "options": ["120 cách", "24 cách", "25 cách", "60 cách"], "answer": "120 cách", "timeLimitSeconds": 20},
        {"id": "g10-tt-22", "text": "Khí nào sau đây có tính tẩy màu ẩm và sát trùng nước sinh hoạt bể bơi?", "options": ["Cl2 (Clo)", "O2", "N2", "CO2"], "answer": "Cl2 (Clo)", "timeLimitSeconds": 20},
        {"id": "g10-tt-23", "text": "Một lực F = 50 N tác dụng vào vật làm vật dịch chuyển quãng đường s = 4m theo hướng của lực. Công sinh ra là:", "options": ["200 J", "100 J", "12,5 J", "54 J"], "answer": "200 J", "timeLimitSeconds": 20},
        {"id": "g10-tt-24", "text": "Chất nào sau đây là ví dụ của polisaccarit (carbohydrate đa phân tử)?", "options": ["Tinh bột", "Glucozơ", "Fructozơ", "Saccarozơ"], "answer": "Tinh bột", "timeLimitSeconds": 20},
        {"id": "g10-tt-25", "text": "Văn minh Hy Lạp và La Mã cổ đại hình thành bên bờ biển nào?", "options": ["Địa Trung Hải", "Biển Đỏ", "Biển Baltic", "Biển Caspi"], "answer": "Địa Trung Hải", "timeLimitSeconds": 20},
        {"id": "g10-tt-26", "text": "Khoảng cách từ điểm M(1; 2) đến đường thẳng Delta: 3x + 4y + 4 = 0 bằng bao nhiêu?", "options": ["3", "15", "5", "2,5"], "answer": "3", "timeLimitSeconds": 20},
        {"id": "g10-tt-27", "text": "Liên kết hydrogen hình thành chủ yếu giữa nguyên tử hiđro liên kết cộng hóa trị với nguyên tử nào sau đây?", "options": ["N, O hoặc F", "C hoặc Si", "Na hoặc K", "Cl hoặc Br"], "answer": "N, O hoặc F", "timeLimitSeconds": 20},
        {"id": "g10-tt-28", "text": "Mômen của một lực F đối với một trục quay có cánh tay đòn d được xác định bằng công thức:", "options": ["M = F . d", "M = F / d", "M = F . d^2", "M = 1/2 . F . d"], "answer": "M = F . d", "timeLimitSeconds": 20},
        {"id": "g10-tt-29", "text": "Enzyme có bản chất hóa học chủ yếu là chất gì?", "options": ["Protein", "Lipid", "Axit nucleic", "Gluxit"], "answer": "Protein", "timeLimitSeconds": 20},
        {"id": "g10-tt-30", "text": "Tác phẩm 'Bình Ngô đại cáo' được viết sau thắng lợi trọn vẹn của cuộc khởi nghĩa nào?", "options": ["Khởi nghĩa Lam Sơn", "Khởi nghĩa Tây Sơn", "Khởi nghĩa Hai Bà Trưng", "Khởi nghĩa Bãi Sậy"], "answer": "Khởi nghĩa Lam Sơn", "timeLimitSeconds": 20}
    ],
    "finish": [
        {"id": "g10-vd-10-4", "points": 10, "text": "Số tập hợp con của một tập hợp gồm 3 phần tử là bao nhiêu?", "answer": "8 tập hợp con (2^3)"},
        {"id": "g10-vd-10-5", "points": 10, "text": "Quy tắc bát tử (octer rule) nêu xu hướng các nguyên tử đạt cấu hình electron bền vững của khí hiếm với bao nhiêu electron ở lớp ngoài cùng?", "answer": "8 electron (trừ He có 2)"},
        {"id": "g10-vd-10-6", "points": 10, "text": "Định luật bảo toàn cơ năng chỉ nghiệm đúng khi vật chuyển động trong trường lực nào?", "answer": "Trường lực thế (chỉ chịu tác dụng của trọng lực, lực đàn hồi, không có ma sát)"},
        {"id": "g10-vd-10-7", "points": 10, "text": "Tác phẩm sử thi cổ Hy Lạp kể về cuộc chiến thành Troy và hành trình trở về quê hương của dũng sĩ Odysseus là tác phẩm nào?", "answer": "Odyssey (Ô-đi-xê) và Iliad (I-li-át)"},
        {"id": "g10-vd-10-8", "points": 10, "text": "Virus có cấu tạo tế bào hoàn chỉnh hay không?", "answer": "Không (chưa có cấu tạo tế bào)"},
        {"id": "g10-vd-10-9", "points": 10, "text": "Nguyên tố halogen nào duy nhất ở thể lỏng ở nhiệt độ thường có màu nâu đỏ?", "answer": "Brom (Br2)"},
        {"id": "g10-vd-10-10", "points": 10, "text": "Kinh thành Thăng Long thời Lý - Trần - Lê được bao bọc bởi vòng thành lớn ngoài cùng mang tên gì?", "answer": "La Thành (Đại La)"},
        {"id": "g10-vd-20-4", "points": 20, "text": "Tìm tập nghiệm của bất phương trình bậc hai: x^2 - 5x + 6 < 0?", "answer": "Khoảng (2; 3)"},
        {"id": "g10-vd-20-5", "points": 20, "text": "Tính số hạt nơtron có trong hạt nhân của nguyên tử đồng vị Nhôm 27/13 Al?", "answer": "14 hạt nơtron"},
        {"id": "g10-vd-20-6", "points": 20, "text": "Một lò xo có độ cứng k = 100 N/m bị nén một đoạn 0,1 m so với trạng thái tự nhiên. Thế năng đàn hồi tích lũy trong lò xo là bao nhiêu Jun?", "answer": "0,5 J"},
        {"id": "g10-vd-20-7", "points": 20, "text": "Bài thơ 'Cảnh ngày hè' (Bảo kính cảnh giới số 43) thể hiện tấm lòng yêu nước thương dân thiết tha của danh nhân văn hóa nào?", "answer": "Nguyễn Trãi"},
        {"id": "g10-vd-20-8", "points": 20, "text": "Hai nhà khoa học nào đã khám phá ra mô hình cấu trúc xoắn kép của phân tử ADN vào năm 1953?", "answer": "James Watson và Francis Crick"},
        {"id": "g10-vd-20-9", "points": 20, "text": "Hiện tượng uốn nếp và đứt gãy các tầng đất đá trong thạch quyển là do tác động chủ yếu của lực nào?", "answer": "Nội lực"},
        {"id": "g10-vd-20-10", "points": 20, "text": "Bộ chính sử biên niên đầu tiên của nước Đại Việt do nhà sử học Lê Văn Hưu soạn thảo dưới triều Trần có tên là gì?", "answer": "Đại Việt sử ký"},
        {"id": "g10-vd-30-4", "points": 30, "text": "Trong mặt phẳng tọa độ Oxy, cho tam giác ABC có A(1; 3), B(4; 2), C(-2; 1). Tìm tọa độ trọng tâm G của tam giác ABC?", "answer": "G(1; 2)"},
        {"id": "g10-vd-30-5", "points": 30, "text": "Cân bằng phản ứng oxi hóa - khử sau theo phương pháp thăng bằng electron: Cu + HNO3 (loãng) -> Cu(NO3)2 + NO + H2O. Tổng hệ số nguyên tối giản của phương trình là bao nhiêu?", "answer": "Tổng hệ số là 20 (3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O)"},
        {"id": "g10-vd-30-6", "points": 30, "text": "Một viên đạn khối lượng 10g bay với vận tốc 400 m/s xuyên vào một bao cát đứng yên và nằm yên trong đó. Độ biến thiên động lượng của viên đạn là bao nhiêu kg.m/s?", "answer": "-4 kg.m/s (độ lớn là 4 kg.m/s)"},
        {"id": "g10-vd-30-7", "points": 30, "text": "Một tế bào sinh dưỡng (2n = 14) trải qua 4 lần nguyên phân liên tiếp. Tính số tế bào con được tạo thành sau quá trình đó?", "answer": "16 tế bào con"},
        {"id": "g10-vd-30-8", "points": 30, "text": "Gieo đồng thời hai con xúc xắc cân đối và đồng chất. Tính xác suất để tổng số chấm xuất hiện trên hai mặt bằng 7?", "answer": "1/6 (6/36)"},
        {"id": "g10-vd-30-9", "points": 30, "text": "Hệ thống kênh đào thủy lợi cổ đại Grand Canal (Đại Vận Hà) nối hai con sông Hoàng Hà và Trường Giang ở Trung Quốc được bắt đầu xây dựng từ triều đại phong kiến nào?", "answer": "Nhà Tùy"},
        {"id": "g10-vd-30-10", "points": 30, "text": "Giải thích vì sao nước biển ở vùng xích đạo thường có độ muối thấp hơn nước biển ở vùng chí tuyến?", "answer": "Vì vùng xích đạo có lượng mưa rất lớn và độ bốc hơi thấp hơn vùng chí tuyến nhiều nắng ít mưa"}
    ]
}
